fix: (#1002): Добавлена обработка заголовка "Range" объекта HTTPЗапрос.
EvilBeaver/OneScript pull request #1003
Opened 2020-04-23 20:08 UTC by arkuznetsov

2020-04-24 12:56 UTC, EvilBeaver requested changes

2020-04-24 12:56 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Http/HttpConnectionContext.cs
> +                        {
Мне не нравится идея засовывания всего в 1 файл и приватного класса-парсера здесь же.
А без парсера, простая установка заголовка по текстовому имени "Range" - не работает?

2020-04-24 15:39 UTC, arkuznetsov commented on src/ScriptEngine.HostedScript/Library/Http/HttpConnectionContext.cs
> +                        {
Там у webRequest для range есть только метод AddRange(string, int, int), AddRange(string, int), AddRange(int), а по спеке в заголовке можно указывать несколько диапазонов, так что без парсера ни как :-(.
Парсер - не класс, парсер - функция. Класс (Range) это элемент результата.
Порекомендуй как правильнее оформить, переделаю.

2020-04-25 15:23 UTC, arkuznetsov commented on src/ScriptEngine.HostedScript/Library/Http/HttpConnectionContext.cs
> +                        {
Может вообще всю логику SetRequestHeaders в отдельный модуль вынести?

2020-04-27 18:25 UTC, EvilBeaver approved these changes

2020-04-27 18:25 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Http/HttpConnectionContext.cs
> +                        {
Ну раз функция, то уже не так плохо... Не углядел.

2020-05-04 08:48 UTC, EvilBeaver commented
@arkuznetsov подтяни, пожалуйста, свежие изменения из develop - ошибка компиляции пропадет

2020-05-04 11:31 UTC, merged