WIP: поддержка ком объектов при дебаге
EvilBeaver/OneScript pull request #1007
Opened 2020-05-07 03:50 UTC by ArchLord42RU

see: #999

2020-05-07 14:00 UTC, EvilBeaver requested changes

2020-05-07 14:00 UTC, EvilBeaver commented on src/ScriptEngine/Machine/RcwMembersCollection.cs
> +            _identifiers = new Dictionary<string, int>(StringComparer.InvariantCultureIgnoreCase);
Есть коллекция IndexedNameCollection которая как раз управляет привязкой имен к числовым номерам, много где используется

2020-05-07 14:00 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/UnmanagedRCWComContext.cs
> +                    throw e.InnerException ?? e;
А что, есть ситуации, когда TargetInvocationException не содержит InnerExeption?

2020-05-07 14:00 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/UnmanagedRCWComContext.cs
> +            return _props.Value.Count;
Есть предложение - обернуть _props.Value в отдельное свойство, т.к. много где повторяется этот вызов

2020-05-08 15:11 UTC, ArchLord42RU commented on src/ScriptEngine/Machine/Contexts/UnmanagedRCWComContext.cs
> +                    throw e.InnerException ?? e;
Теоретически - да
`public Exception? InnerException`

2020-05-08 23:57 UTC, closed without merging