Получение текущего ЦветаТекста/Фона консоли в Try-Catch
EvilBeaver/OneScript pull request #1040
Opened 2020-11-02 08:42 UTC by 240596448

<Fix for PowerShell>
https://t.me/oscript_library/32965

При получении из перечисления "неустановленного" цвета валится ошибка.
Характерно для PowerShell и при запуске Cmd из PS (в Cmd после установки цвета получение происходит корректно)

2020-11-02 08:47 UTC, 240596448 commented
Проверил руками - возвращает "неопределено"

2020-11-03 18:26 UTC, EvilBeaver requested changes

2020-11-03 18:26 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +                catch
Нужно поймать конкретный тип исключения, который возникает при запуске в консоли PowerShell и считать нормой только его

2020-11-03 20:49 UTC, 240596448 commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +                catch
Согласен. Но я такую обработку не осилю.
А тип ошибки известен:
{Модуль C:\Oscripts\temp\ЦветнойВывод.os / Ошибка в строке: 142 / Внешнее исключение (System.InvalidOperationException): Последовательность не содержит соответствующий элемент}

2020-11-03 21:04 UTC, 240596448 commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +                catch
> Нужно поймать конкретный тип исключения, который возникает при запуске в консоли PowerShell и считать нормой только его

Добавил коммит ниже. Так правильно?

2020-11-06 12:34 UTC, EvilBeaver approved these changes

2020-11-06 12:34 UTC, merged