LRE трасировщик ядра
EvilBeaver/OneScript pull request #1054
Opened 2020-12-20 03:49 UTC by aliczin

умеет определять переменную окружения `OS_LRE_TRACE`

выводит отладочную информацию о загрузке библиотек
полезен при отладке хаоса зависимостей и кастомных загрузчиков

чтобы попробовать и увидеть что у нас творится с загрузкой библиотек делаем следующее

```
set OS_LRE_TRACE=1
opm install 1testrunner
```

![изображение](https://user-images.githubusercontent.com/56105699/102704652-53e1de00-428f-11eb-90d8-e4a88250d5f8.png)

дополнительно добавлен тест на загрузку библиотек каскадом.

2020-12-21 09:06 UTC, EvilBeaver commented
что такое LRE?

2020-12-21 09:08 UTC, EvilBeaver requested changes

2020-12-21 09:08 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/LibraryResolver.cs
> +                Console.WriteLine("LRE: " + message);
Здесь нужна какая-то абстракция, хотя бы SystemLog.Write. Дело в том, что может быть GUI-приложение без консоли, например TestApp или Обновлятор или ТурбоКонф

2020-12-21 09:21 UTC, aliczin commented on src/ScriptEngine.HostedScript/LibraryResolver.cs
> +                Console.WriteLine("LRE: " + message);
@EvilBeaver а есть пример ?

2020-12-21 09:22 UTC, aliczin commented on src/ScriptEngine.HostedScript/LibraryResolver.cs
> +                Console.WriteLine("LRE: " + message);
> 
> 
> что такое LRE?

Library Resolver Enviroment - чтобы отличать вывод.

2020-12-21 09:43 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/LibraryResolver.cs
> +                Console.WriteLine("LRE: " + message);
> @EvilBeaver а есть пример ?

https://github.com/EvilBeaver/OneScript/blob/dc158529d67bf780c9116571f7ddae278fe6dbfa/src/ScriptEngine/Machine/Contexts/AutoContext.cs#L95

2020-12-21 11:21 UTC, EvilBeaver approved these changes

2020-12-21 11:21 UTC, merged

2020-12-21 11:24 UTC, Mr-Rm commented
Не следует ли вынести ```GetEnvironmentVariable("OS_LRE_TRACE")``` в инициализацию ScriptEnginе или, по крайней мере в конструктор LibraryResolver? Иначе в поцессе  загрузки библиотек трассировка может произвольно включаться/выключаться.
Или вместо переменной среды задействовать параметр oscript?

2020-12-22 11:37 UTC, EvilBeaver commented
@Mr-Rm да, следует, но я решил не придираться и исправить самому. @aliczin и так считает, что я придираюсь по пустякам.

2020-12-22 11:42 UTC, aliczin commented
@EvilBeaver я все исправлял что сказано - скажите исправить я исправлю - только можно не по одному комменту в месяц. @Mr-Rm скажи как сделать лучше - я сделаю.

Сразу отревьюить и всё. ;-)