Чтение запись свойств через точку
EvilBeaver/OneScript pull request #1079
Opened 2021-04-26 10:57 UTC by dmpas

2021-04-26 11:21 UTC, EvilBeaver requested changes

2021-04-26 11:21 UTC, EvilBeaver commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +                    if (!typeof(IRuntimeContextInstance).IsAssignableFrom(expression.Type))
ойой, ненене, не надо в эту сборку зависимость от IRuntimeContextInstance!

2021-04-26 11:21 UTC, EvilBeaver commented on src/OneScript.Native/OneScript.Native.csproj
> +        <ProjectReference Include="..\ScriptEngine\ScriptEngine.csproj" />
нет, вот этой зависимости тут не должно быть

2021-04-26 11:21 UTC, EvilBeaver commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +                    var miFindProperty = topType.GetMethod("FindProperty",
Этот протокол лучше заделегировать на DLR. Там в базовых классах в `ContextIValueImpl` уже определен метод DRL TryGetMember который вызывает нужные FindProperty.

А тут в компиляторе нужно проверить тип переменной. Если он BslObjectValue (см метод-расширение `IsObjectValue()`) - то можно поискать свойство обычной рефлексией, так же как сделано для методов. А если это Структура (т.е. объект с динамическим составом свойств) или просто BslValue неизвестного типа- то пусть Dlr с ним разбирается.

2021-04-26 11:23 UTC, EvilBeaver commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +                    var a = info.CustomAttributes.FirstOrDefault(data =>
см. класс ContextMethodsCache лучше это куда-то туда вынести.

2021-04-26 12:30 UTC, dmpas commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +                    if (!typeof(IRuntimeContextInstance).IsAssignableFrom(expression.Type))
выпилed

2021-04-26 12:31 UTC, dmpas commented on src/OneScript.Native/OneScript.Native.csproj
> +        <ProjectReference Include="..\ScriptEngine\ScriptEngine.csproj" />
выпилed

2021-04-26 12:31 UTC, dmpas commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +                    var a = info.CustomAttributes.FirstOrDefault(data =>
принял

2021-04-26 14:35 UTC, EvilBeaver requested changes

2021-04-26 14:35 UTC, EvilBeaver commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +                var valueToSet = _statementBuildParts.Pop();
Может разнести тела этих 2 веток if-else по двум методам?

2021-04-26 14:35 UTC, EvilBeaver commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +                if (!toWrite && false)
что такое && false?

2021-04-26 15:21 UTC, dmpas commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +                if (!toWrite && false)
это штука с кастом в BslValue, которую я хочу тебе показать. Убираем && false и падает другой тест. В телеге писал про это.

2021-04-28 07:52 UTC, EvilBeaver commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +using ScriptEngine.Machine;
кхыы кхыыыы, зачем оно сюда пролезло опять....

2021-04-28 07:55 UTC, dmpas commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +using ScriptEngine.Machine;
я дико извиняюсь, но:
https://github.com/EvilBeaver/OneScript/blob/native/src/OneScript.Core/Values/IValue.cs#L10

2021-04-28 07:56 UTC, EvilBeaver commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +using ScriptEngine.Machine;
но в классе нет упоминания IValue вроде как. Или есть?

2021-04-28 07:57 UTC, EvilBeaver commented on src/OneScript.Native/Compiler/MethodCompiler.cs
> +using ScriptEngine.Machine;
Я слепой. Тыща извинений.

2021-04-28 07:57 UTC, EvilBeaver approved these changes

2021-04-28 07:57 UTC, merged