feat (#746): Реализована возможность чтения из скрипта данных, переданных через stdin
EvilBeaver/OneScript pull request #1086
Opened 2021-05-26 14:31 UTC by arkuznetsov

Реализована возможность чтения из скрипта данных, переданных через stdin.

test.os
```bsl
Чтение = Новый ЧтениеТекста();
Чтение.Открыть(СтандартныйПотокВвода);
Сообщить(СокрЛП(Чтение.Прочитать()));
```

Запускаем:
```bat
> echo 1234 | oscript test.os
```

Вывод:
```
1234
```

2021-05-26 14:41 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            RegisterProperty("СтандартныйПотокВвода", () => StandartInput);
Давай сделаем это не глобальным свойством, а в классе Консоль? Не хочется занимать глобальный неймспейс без нужды... @nixel2007 @artbear @dmpas @Infactum - реквестирую консилиум.

2021-05-26 14:41 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +                GenericStream ConsoleInput = new GenericStream(Console.OpenStandardInput(), true);
Мне больше нравится API Console.OpenStandardInput() который вызывается, как метод-действие по требованию.

2021-05-26 14:43 UTC, arkuznetsov commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            RegisterProperty("СтандартныйПотокВвода", () => StandartInput);
А в таком случае, как должно выглядеть обращение из скрипта?

2021-05-26 14:45 UTC, arkuznetsov commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +                GenericStream ConsoleInput = new GenericStream(Console.OpenStandardInput(), true);
Ты предлагаешь, сделать типа:
```bsl
Консоль = Новый Консоль();
Консоль.ПолучитьСтандартныйВвод();
```
?

2021-05-26 14:56 UTC, nixel2007 commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            RegisterProperty("СтандартныйПотокВвода", () => StandartInput);
я могу поделиться примерами из java.

Обычно работа с потоком ввода идет через объект `System.in`, который держит ссылку на `InputStream`, у которого есть read-методы по чтению сырых байтов. При этом есть класс `Console`, ссылка на который лежит там же в `System.console()`. Там методы уже покрасивее, есть readLine, format, readPassword и прочая красота.

При этом запись в stdout может выполняться как из `System.out` так и из `System.console()`.

System.in появился в 1.1, то есть грубо говоря на заре появления джавы. Console - уже в 1.6, то есть некоторого после взятия за голову.

Но на практике напрямую из потоков и/или консоли все равно никто не читает, а оборачивают обращения к System.in через вызовы `Scanner` (который умеет `readInt`, `readFloat` и прочее) либо в `InputStreamReader`.

---

Занимать глобальный нэймспэйс точно не хочется. Перенести поток в `Консоль` выглядит вполне логично и похоже на ту же джаву. Поток же все равно нельзя будет получить, если скрипт запущен не из терминала, да? помню, что обращение к `Консоль` падает при запуске в определенных вне-терминальных окружениях. Не будет ли здесь проблем?

2021-05-27 09:20 UTC, arkuznetsov commented
Хм, чот на Linux не отрабатывает. :-(
@EvilBeaver @dmpas Что может быть?

2021-05-27 15:26 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +                GenericStream ConsoleInput = new GenericStream(Console.OpenStandardInput(), true);
Да. Консоль.ОткрытьПотокВвода(), например

2021-05-27 15:27 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            RegisterProperty("СтандартныйПотокВвода", () => StandartInput);
> Хм, чот на Linux не отрабатывает. :-(
> @EvilBeaver @dmpas Что может быть?

Все что угодно. Как именно оно не отрабатывает? Ругается на что-то?

2021-05-27 15:28 UTC, EvilBeaver commented
> Хм, чот на Linux не отрабатывает. :-(
> @EvilBeaver @dmpas Что может быть?

Все что угодно. Как именно оно не отрабатывает? Ругается на что-то? Есть тексты ошибок?

2021-05-27 15:44 UTC, arkuznetsov commented
> > Хм, чот на Linux не отрабатывает. :-(
> > @EvilBeaver @dmpas Что может быть?
> 
> Все что угодно. Как именно оно не отрабатывает? Ругается на что-то? Есть тексты ошибок?

Просто не получает данные с stdin. Без ошибок. Руками не запускал, просто тесты посмотрел.

2021-05-28 08:06 UTC, EvilBeaver commented
Я не знаю. Предлагаю копать дальше. Погуглить известные баги в mono или core (смотря под чем гоняешь тесты)

2021-05-28 09:09 UTC, arkuznetsov commented
> Я не знаю. Предлагаю копать дальше. Погуглить известные баги в mono или core (смотря под чем гоняешь тесты)

Да, конечно, буду ковырять. А тесты я на твоем Женькинсе смотрел :-).

2021-05-28 14:04 UTC, arkuznetsov commented
@EvilBeaver Переделал.

2021-05-28 14:10 UTC, EvilBeaver requested changes

2021-05-28 14:10 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            RegisterProperty("Символы", () => (IValue)Chars);
Вот сюда бы добавить свойство Консоль, чтобы был глобальный синглтон. @dmpas, что думаешь?

2021-05-28 14:10 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +                lock (_lock)
lock не нужен, см. статью Скита про синглоны. Нужно создать пустой статик конструктор и обычное статическое поле. https://csharpindepth.com/articles/singleton

Варианты 5 и 6

2021-05-28 14:10 UTC, nixel2007 commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +            if (_console == null)
если это попытка в DLC, то в мультитреде оно работает не так, как ты ожидаешь.

https://csharpindepth.com/articles/singleton

2021-05-28 14:14 UTC, arkuznetsov commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            RegisterProperty("Символы", () => (IValue)Chars);
> Вот сюда бы добавить свойство Консоль, чтобы был глобальный синглтон. @dmpas, что думаешь?

Уже сразу в тестах нарвался на 'Консоль = Новый Консоль()' боюсь, что много где может вылезти.

2021-05-28 14:18 UTC, arkuznetsov commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +                lock (_lock)
Опять же оставил конструктор, чтобы не ломать совместимость. С lock посмотрю.

2021-05-28 14:26 UTC, nixel2007 commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            RegisterProperty("Символы", () => (IValue)Chars);
может не глобальный, а через враппер? типа Система?
я помню, что вы наоборот выносили из системной информации всякие методы и свойства наружу, но может просто было нехорошее имя?

2021-07-25 07:10 UTC, arkuznetsov commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +        [ContextProperty("КодировкаВыходногоПотока", "InputEncoding")]
Наверное "КодировкаВходногоПотока".

2021-07-25 07:20 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +        [ContextProperty("КодировкаВыходногоПотока", "InputEncoding")]
Нет, тут именно Выходного. Их там две. Но английский синоним забыл поменять после копипасты. Спасибо

2021-07-25 08:55 UTC, arkuznetsov commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +        [ContextProperty("КодировкаВыходногоПотока", "InputEncoding")]
Угу, не туда посмотрел.

2021-07-27 09:24 UTC, EvilBeaver approved these changes

2021-07-27 09:25 UTC, merged