ХешированиеДанных поддержка потоков Closes #1083
EvilBeaver/OneScript pull request #1097
Opened 2021-06-30 13:24 UTC by Chipazawra

Closes #1083
Поправил работу с потоками в ХешированииДанных

2021-06-30 14:00 UTC, EvilBeaver requested changes

2021-06-30 14:00 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Binary/GenericStream.cs
> +        long Size();
А это зачем? Все эти методы же можно достать из самого стрима, который отдаст GetUnderlyingStream?

2021-06-30 14:00 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Hash/HashImpl.cs
>                      var length = Math.Min(count == 0 ? stream.Size() : count, stream.Size() - stream.CurrentPosition());
Здесь надо вызвать получение родного Stream через метод getUnderlyingStream и позицию и размер брать из родного системного стрима. Можем обсудить в личке в телеге, если хочешь.

2021-07-02 09:00 UTC, Chipazawra commented
Тестов пройдено: 595

Тестов не пройдено: 4
    * ТестДолжен_ПроверитьПодключениеВнешнейКомпонентыZIP : <C:\Users\--\OneScript\tests\native-api.os>
    * ТестДолжен_ПроверитьПодключениеВнешнейКомпонентыDLL : <C:\Users\--\OneScript\tests\native-api.os>
    * ТестДолжен_ПроверитьСвойстваВнешнейКомпоненты : <C:\Users\--\OneScript\tests\native-api.os>
    * ТестДолжен_ПроверитьМетодыВнешнейКомпоненты : <C:\Users\--\OneScript\tests\native-api.os>

Тестов не реализовано \ пропущено: 2
    * ТестДолжен_СоздатьСокет : <C:\Users\--\OneScript\tests\socket.os>
    * ТестДолжен_ПроверитьВыбросИсключенияНаНеверномМакете : <C:\Users\--\OneScript\tests\templates.os>

2021-07-02 11:10 UTC, EvilBeaver commented
Эти тесты могут падать.

2021-07-02 11:10 UTC, merged