Добавил "1C (BSL)" для поиска отладчика
EvilBeaver/OneScript pull request #1129
Opened 2021-09-22 11:18 UTC by artbear

Сценарий:
у меня не был установлен отладчик
я нажал Ф5, ВСКод предложили найти отладчик
автоматом подставила строку @category:"Debuggers" 1C (BSL) в панели расширений
и там нет нашего отладчика
есть только расширение Исполнитель от 1С

предложение - хорошо бы добавить свойства и нашему отладчику, чтобы быстро и сразу искался

![image](https://user-images.githubusercontent.com/2920817/134334323-e0d433e0-d8c9-4dc6-8c7d-02b98a24daa5.png)

2021-09-22 11:48 UTC, EvilBeaver requested changes

2021-09-22 11:48 UTC, EvilBeaver commented on src/VSCode.DebugAdapter/package.json
> +  "displayName": "OneScript Debug 1C (BSL)",
Я бы убрал слово 1С отсюда, т.к. 1С они не отлаживает, и вообще копирайты, то, сё.

2021-09-22 15:07 UTC, artbear commented on src/VSCode.DebugAdapter/package.json
> +  "displayName": "OneScript Debug 1C (BSL)",
@EvilBeaver как я в чате сегодня писал, такое сочетание подставляется средой ВСКод.
А она получает его из представления языка, которое отдается плагином BSL LS.

Там-то вполне себе юзается такое сочетание
Предлагаю и здесь оставить именно это сочетание 1C (BSL)

2021-09-26 11:01 UTC, EvilBeaver commented on src/VSCode.DebugAdapter/package.json
> +  "displayName": "OneScript Debug 1C (BSL)",
отладчик не связан с плагином VSC для BSL, он не отлаживает код 1С, он узко заточен на 1скрипт. Не надо вводить пользователей в заблуждение

2021-09-26 15:59 UTC, artbear commented on src/VSCode.DebugAdapter/package.json
> +  "displayName": "OneScript Debug 1C (BSL)",
@EvilBeaver оставил только (BSL)

2021-09-26 19:26 UTC, merged