feat: Реализован класс ПреобразованиеXSL и тесты к нему.
EvilBeaver/OneScript pull request #1193
Opened 2022-10-02 18:34 UTC by arkuznetsov

2022-10-02 19:19 UTC, EvilBeaver requested changes

2022-10-02 19:19 UTC, EvilBeaver commented on src/OneScript.StandardLibrary/Xml/XSLTransform.cs
> +            if (!(xmlNode.GetRawValue() is BslObjectValue))
Я тут подумал, вот это объект xmlNode - он какого типа реально? Можно просто в начале метода ведь написать явный тип`void LoadXSLStylesheetFromNode(XmlNode xmlNode)` и проверка типа будет выполняться сама и выбрасываться правильное исключение. А вот этот if можно будет убрать изо всех методов

2022-10-02 19:19 UTC, EvilBeaver commented on src/OneScript.StandardLibrary/Xml/XSLTransform.cs
> +            if (!(xmlNode.GetRawValue() is BslObjectValue))
Можно вместо IValue написать явный тип и проверка будет работать автоматически

2022-10-02 19:19 UTC, EvilBeaver commented on src/OneScript.StandardLibrary/Xml/XSLTransform.cs
> +            if (value.SystemType == BasicTypes.Boolean)
Вместо if-elseif можно вызвать `ContextValuesMarshaller.CastToClrObject(value)`

2022-10-02 19:32 UTC, arkuznetsov commented on src/OneScript.StandardLibrary/Xml/XSLTransform.cs
> +            if (!(xmlNode.GetRawValue() is BslObjectValue))
А что, теперь так можно, Раньше вроде все "сложные" типы можно только через IValue было передавать, нет? XmlNode - это дотнетовский тип, а не оскрипта.

2022-10-02 19:40 UTC, arkuznetsov commented on src/OneScript.StandardLibrary/Xml/XSLTransform.cs
> +            if (!(xmlNode.GetRawValue() is BslObjectValue))
Похоже, что это я вообще накосячил, надо подумать. Или оставить NotEplemented. :-)

2022-10-02 20:02 UTC, EvilBeaver commented on src/OneScript.StandardLibrary/Xml/XSLTransform.cs
> +            if (!(xmlNode.GetRawValue() is BslObjectValue))
> Похоже, что это я вообще накосячил

Ну да, чисто дотнетовский тип вообще никак из скрипта не попадет в этот метод. Откуда он получается вообще?

2022-10-02 20:21 UTC, arkuznetsov commented on src/OneScript.StandardLibrary/Xml/XSLTransform.cs
> +            if (!(xmlNode.GetRawValue() is BslObjectValue))
Видимо я не нашел оскриптовую реализацию XmlNode, а дальше фигню сморозил. Поразбираюсь.

2022-10-02 20:29 UTC, arkuznetsov commented on src/OneScript.StandardLibrary/Xml/XSLTransform.cs
> +            if (!(xmlNode.GetRawValue() is BslObjectValue))
А, я понял, DOM же не реализован, так что проще оставить NotEmplemented пока кому-нить DOM не понадобится (32 дополнительных классов оберток).

2022-10-03 09:09 UTC, EvilBeaver approved these changes

2022-10-03 09:11 UTC, merged