Поправлен тест чтения stdin
EvilBeaver/OneScript pull request #1210
Opened 2022-10-27 09:07 UTC by arkuznetsov

2022-10-27 12:40 UTC, otymko commented on tests/process.os
> +	Сообщить("<PID>");
@arkuznetsov, не совсем понятно, зачем именно это сообщение (

2022-10-27 13:45 UTC, EvilBeaver requested changes

2022-10-27 13:45 UTC, EvilBeaver commented on tests/console.os
> +	Сообщить(СтрШаблон("Исполняемая команда 2: %1", ИсполняемаяКоманда));
Это отладочное как я понял и в конечном варианте не нужно?

2022-10-27 13:45 UTC, EvilBeaver commented on tests/console.os
> +	Сообщить(СтрШаблон("Исполняемая команда 1: %1", ИсполняемаяКоманда));
Это отладочное как я понял и в конечном варианте не нужно?

2022-10-27 13:45 UTC, EvilBeaver commented on tests/console.os
> +	Сообщить(СтрШаблон("Путь к oscript: %1", ПутьКОскрипт));
Это отладочное как я понял и в конечном варианте не нужно?

2022-10-27 13:45 UTC, EvilBeaver commented on tests/console.os
> +	Сообщить(СтрШаблон("Вывод команды: %1", ВыводКоманды));
Это отладочное как я понял и в конечном варианте не нужно?

2022-10-27 14:04 UTC, arkuznetsov commented on tests/process.os
> +	Сообщить("<PID>");
Искал, что не так :-)

2022-10-27 14:04 UTC, arkuznetsov commented on tests/console.os
> +	Сообщить(СтрШаблон("Исполняемая команда 2: %1", ИсполняемаяКоманда));
Да, искал, что не так

2022-10-27 14:04 UTC, arkuznetsov commented on tests/console.os
> +	Сообщить(СтрШаблон("Исполняемая команда 1: %1", ИсполняемаяКоманда));
Да, искал, что не так

2022-10-27 14:05 UTC, arkuznetsov commented on tests/console.os
> +	Сообщить(СтрШаблон("Путь к oscript: %1", ПутьКОскрипт));
Да, искал, что не так

2022-10-27 14:05 UTC, arkuznetsov commented on tests/console.os
> +	Сообщить(СтрШаблон("Вывод команды: %1", ВыводКоманды));
Да, искал, что не так

2022-10-27 15:19 UTC, EvilBeaver approved these changes

2022-10-28 03:23 UTC, otymko commented on tests/console.os
> +	Сообщить(СтрШаблон("Вывод команды: %1", ВыводКоманды));
@arkuznetsov, одно отладочное осталось, оно нужно?

2022-10-28 03:35 UTC, arkuznetsov commented on tests/console.os
> +	Сообщить(СтрШаблон("Вывод команды: %1", ВыводКоманды));
Упс, зевнул, спасибо.

2022-10-28 12:24 UTC, merged