Рефлектор возвращает приватные поля и методы
EvilBeaver/OneScript pull request #1242
Opened 2023-01-02 11:10 UTC by Absolemus

2023-01-02 14:54 UTC, EvilBeaver requested changes

2023-01-02 14:54 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +            return VARIABLE_COUNT + _module.Variables.Count;
Кажется, что так нельзя. Это не сделает доступными к вызову извне приватные переменные и методы?

2023-01-02 14:54 UTC, EvilBeaver commented on src/ScriptEngine/Machine/LoadedModule.cs
> +                        Variables[i] = new VariableInfo()
Этот флаг можно устанавливать сразу при компиляции образа модуля, а не пересоздавать ради него VariableInfo при загрузке LoadedModule

2023-01-02 14:54 UTC, EvilBeaver commented on tests/reflector.os
> +	ТаблицаСвойств = Рефлектор.ПолучитьТаблицуСвойств(Пример);
Мне кажется, надо сделать необязательный второй параметр "ВключаяПриватные" у метода, чтобы не ломать обратную совместимость существующих библиотек. Что-то типа `ПолучитьТаблицуСвойств(Пример, Истина)` вернет в т.ч. приватное.

2023-01-02 15:02 UTC, Absolemus commented on tests/reflector.os
> +	ТаблицаСвойств = Рефлектор.ПолучитьТаблицуСвойств(Пример);
Тогда я возвращаю изменения на место, и для этого флага создаю в рефлекторе для приватных полей/методов новую ветку поведения через Если(ВлючаяПриватные)?

2023-01-02 15:05 UTC, Absolemus commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +            return VARIABLE_COUNT + _module.Variables.Count;
Я думал в этом и смысл, чтобы можно было объявить приватную переменную, а потом в декораторе к ней обратиться)

2023-01-02 17:10 UTC, Absolemus commented on src/ScriptEngine/Machine/LoadedModule.cs
> +                        Variables[i] = new VariableInfo()
Сделать где-нибудь здесь? 
https://github.com/EvilBeaver/OneScript/blob/f9024e3acc4816a535be42cc3bfbdff00e52155e/src/ScriptEngine/Compiler/Compiler.cs#L343
Только там объект создается до того, кака читается токен Экспорт. Как правильно это сделать?

2023-01-03 11:26 UTC, Absolemus commented on src/ScriptEngine/Machine/LoadedModule.cs
> +                        Variables[i] = new VariableInfo()
Сделал

2023-01-03 11:26 UTC, Absolemus commented on tests/reflector.os
> +	ТаблицаСвойств = Рефлектор.ПолучитьТаблицуСвойств(Пример);
Сделал

2023-01-03 11:26 UTC, Absolemus commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +            return VARIABLE_COUNT + _module.Variables.Count;
вернул как было

2023-01-04 10:32 UTC, EvilBeaver requested changes

2023-01-04 10:32 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Reflector.cs
> +                var nativeFields = withPrivate ? clrType.GetFields(BindingFlags.NonPublic | BindingFlags.Public) : clrType.GetFields();
```csharp
var flags = BindingFlags.Public;
if (withPrivate)
    flags |= BindingFlags.NonPublic;

var nativeFields = clrType.GetFields(flags);
```

2023-01-04 10:32 UTC, EvilBeaver commented on src/ScriptEngine/Compiler/Compiler.cs
> +                        {
Ну тут как-то мне не нравится. Ветка создания VariableInfo практически задублирована тут и в ветке else...

Можно создать info, как было раньше, потом прочитать NextToken, и если там Экспорт, то создать ExportedSymbol (как раньше) а в созданную info проставить этот флаг. После чего, info поместить в массив _module.Variables уже в полностью заполненном виде.

2023-01-04 10:32 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Core.cs
> +        public bool IsExport;
с появлением флага isExport получается можно вообще спилить коллекцию ExportedSymbol для переменных, вроде как она не нужна становится

2023-01-04 10:32 UTC, EvilBeaver commented on src/ScriptEngine/Machine/IRuntimeContextInstance.cs
> +                    Index = variable.Index,
Вот с этим индексом и попаданием приватных переменных в выдачу GetPropCount() боюсь, что будут проблемы. Чем отличаются методы GetPropertiesWithoutPrivate и GetPropertiesWithPrivate? Или мы удалили это из ScriptDrivenObject и теперь GetPropCount снова возвращает число только экспортных?

2023-01-04 10:32 UTC, EvilBeaver commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(ТаблицаСвойств[2].Имя, "юТест");
Из теста непонятно, что он проверяет. Что находится в ТаблицаСвойств[0] и ТаблицаСвойств[1]? Почему эти 2 строки исключены из проверки?

2023-01-04 10:32 UTC, EvilBeaver commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(ТаблицаСвойств[2].Имя, "юТест");
Что находится в ТаблицаСвойств[0], 1, 3?

2023-01-04 10:32 UTC, EvilBeaver commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(7, ТаблицаСвойств.Количество());
Почему 7? Ведь по умолчанию второй параметр = Ложь, т.е. приватные не должны попасть в выдачу, разве нет?

2023-01-05 04:15 UTC, Absolemus commented on src/ScriptEngine/Machine/IRuntimeContextInstance.cs
> +                    Index = variable.Index,
GetPropCount возвращает только экспортные. Не стал ломать то, что уже работает и на чем завязана логика. GetPropertiesWithoutPrivate работает как было до моего вмешательства (по умолчанию грубо говоря), GetPropertiesWithPrivate моя новая логика с доступом к приватным переменным

2023-01-05 04:16 UTC, Absolemus commented on src/ScriptEngine/Machine/Core.cs
> +        public bool IsExport;
ExportedSymbol нужна, потому что я не знаю какие еще зависимости лежат на этом объекте.

2023-01-05 04:18 UTC, Absolemus commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(ТаблицаСвойств[2].Имя, "юТест");
Они проверяются тестом выше

2023-01-05 08:27 UTC, EvilBeaver commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(ТаблицаСвойств[2].Имя, "юТест");
Может хотя бы камент? А то спустя месяц уже будет непонятно, а тест, по заветам @artbear должен объяснять, как документация

2023-01-05 08:31 UTC, Absolemus commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(ТаблицаСвойств[2].Имя, "юТест");
Не, я согласен, допишу тесты для остальных элементов. Лишним не будет

2023-01-07 11:36 UTC, Absolemus commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(7, ТаблицаСвойств.Количество());
Исправил

2023-01-07 11:36 UTC, Absolemus commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(ТаблицаСвойств[2].Имя, "юТест");
Добавил

2023-01-07 11:37 UTC, Absolemus commented on src/ScriptEngine.HostedScript/Library/Reflector.cs
> +                var nativeFields = withPrivate ? clrType.GetFields(BindingFlags.NonPublic | BindingFlags.Public) : clrType.GetFields();
Исправил

2023-01-07 11:41 UTC, Absolemus commented on src/ScriptEngine/Compiler/Compiler.cs
> +                        {
Проверь, я чуть изменил создание по твоему комментарию

2023-01-09 11:19 UTC, EvilBeaver requested changes
Огромная просьба упростить метод и если удастся - сразу починить и #1248.

2023-01-09 11:19 UTC, EvilBeaver commented on src/ScriptEngine/Compiler/Compiler.cs
> +                        if(variableInfo.Identifier != null)
Не очень понял изменения... Если _inMethodScope == false то переменная variableInfo как бы и вообще не нужна получается. Она создана конструктором, в ней проставлен IsExport, а потом она никуда не идет, т.к. в ней идентификатор пустой. Кажется, что код слишком запутан, может разбить на несколько методов?

И да, разглядывая этот код я нашел существующую ошибку https://github.com/EvilBeaver/OneScript/issues/1248, спасибо!

2023-01-12 10:42 UTC, EvilBeaver approved these changes
Спасибо! Я готов влить, но если есть желание поправить 2 мелких замечания, я подожду.

2023-01-12 10:42 UTC, EvilBeaver commented on src/NUnitTests/CompilerTests.cs
> +                _ = host.Engine.GetCompilerService().Compile(moduleSource);
Странно, что здесь присваивание. Ведь можно же просто вызвать функцию, как процедуру

``host.Engine.GetCompilerService().Compile(moduleSource);``

2023-01-12 10:42 UTC, EvilBeaver commented on src/NUnitTests/CompilerTests.cs
> +					Перем Переменная Экспорт;
Съехали отступы (лучше использовать пробелы, меньше проблем)

2023-01-12 11:25 UTC, Absolemus commented
Да, давай поправлю

2023-01-12 13:42 UTC, merged