В рефлектор добавлен метод ИзвестныеТипы()
EvilBeaver/OneScript pull request #1368
Opened 2023-10-18 07:05 UTC by sfaqer

Добавлен метод который возвращает все зарегистрированные типы в виде Массив<Тип>

2023-10-18 07:10 UTC, nixel2007 commented
Может вместо голого типа возвращать ещё какие-то метаданные? Типа пользовательский ли это тип (из сценария) или движковый?

2023-10-18 08:03 UTC, sfaqer commented
> Может вместо голого типа возвращать ещё какие-то метаданные? Типа пользовательский ли это тип (из сценария) или движковый?

Типа того?

2023-10-18 08:22 UTC, dmpas commented
Вечный спор между Массивом Структур и Таблицей Значений.

2023-10-18 08:28 UTC, sfaqer commented
> Вечный спор между Массивом Структур и Таблицей Значений.

Можно в теории кстати мапу сделать, с типом на структуру с описанием типа, вероятно так даже удобнее будет 

`ИзвестныеТипы().Получить(Тип).Пользовательский`

2023-10-18 10:45 UTC, nixel2007 commented
Выглядит симпатично, а хватит ли этого для осени - надо пробовать)

2023-10-18 10:51 UTC, EvilBeaver commented
> Может вместо голого типа возвращать ещё какие-то метаданные? Типа пользовательский ли это тип (из сценария) или движковый?

А зачем? _Какую задачу вы планируете этим решить? (C)_

2023-10-18 10:56 UTC, EvilBeaver requested changes

2023-10-18 10:56 UTC, EvilBeaver commented on src/OneScript.StandardLibrary/Reflector.cs
> +        public static IValue CreateNew(TypeActivationContext context)
Лучше сразу ReflectorContext возвращать

2023-10-18 10:56 UTC, EvilBeaver commented on src/ScriptEngine/Machine/DefaultTypeManager.cs
> +            return _knownTypes;
Возвращаемое значение лучше указать, как IReadOnlyList<>

2023-10-18 10:56 UTC, EvilBeaver commented on src/OneScript.StandardLibrary/Reflector.cs
> +            _typeManager.RegisteredTypes()
Во всех прочих местах рефлектор отдает ТаблицуЗначений. Предлагаю здесь так же. Заодно можно будет по ней делать НайтиСтроки для всех пользовательских, например. Предлагаю колонки:

* Имя
* Значение(тип Тип)
* Примитивный
* Пользовательский
* Коллекция

2023-10-18 10:59 UTC, EvilBeaver commented on src/OneScript.StandardLibrary/Reflector.cs
> +            _typeManager.RegisteredTypes()
А, ну и в метод ИзвестныеТипы() можно сразу сделать опциональный параметр Фильтр, который будет работать, как НайтиСтроки для этой таблицы значений

2023-10-18 11:58 UTC, sfaqer commented
@EvilBeaver Поправил по замечаниям =)

2023-10-19 15:56 UTC, EvilBeaver commented
@sfaqer спасибо, кажется, что огнищще!

2023-10-19 15:57 UTC, merged