В веб-сервер добавлена возможность работы с данными форм.
EvilBeaver/OneScript pull request #1476
Opened 2024-12-06 23:38 UTC by akpaevj

Доработка по #1473.  В веб-сервер добавлена возможность работы с данными форм в контексте запроса

Breaking changes: изменен тип значения у значений хедеров. Теперь это коллекция строк, а не примитивный тип

2024-12-10 07:29 UTC, EvilBeaver requested changes

2024-12-10 07:29 UTC, EvilBeaver commented on src/OneScript.Web.Server/FormCollectionWrapper.cs
> +		public StringValuesWrapper Retrieve(IValue key)
Почему бы и сам метод не назвать Get?

2024-12-10 07:29 UTC, EvilBeaver commented on src/OneScript.Web.Server/FormCollectionWrapper.cs
> +        public override bool IsIndexed => true;
Отступ

2024-12-10 07:29 UTC, EvilBeaver commented on src/OneScript.Web.Server/HttpRequestWrapper.cs
> +	[ContextClass("HTTPСервисЗапрос", "HTTPServiceRequest")]
Отступы

2024-12-10 07:29 UTC, EvilBeaver commented on src/OneScript.Web.Server/HttpRequestWrapper.cs
> +			}
Тоже что-то с отступами скобок

2024-12-10 07:29 UTC, EvilBeaver commented on src/OneScript.Web.Server/HttpRequestWrapper.cs
> +                    return BslNullValue.Instance;
Null или Undefined? Мне кажется, лучше Неопределено, а не явный Null

2024-12-10 16:52 UTC, akpaevj commented
Поправлю отступы и обновлю пр. Что-то непонятное

2024-12-10 17:50 UTC, akpaevj commented on src/OneScript.Web.Server/HttpRequestWrapper.cs
> +                    return BslNullValue.Instance;
Тогда стоит, наверное, везде поменять (во всем проекте), там есть еще места с null.

2024-12-10 23:16 UTC, nixel2007 commented on src/OneScript.Web.Server/HttpRequestWrapper.cs
> +                    return BslNullValue.Instance;
По одной проблеме за раз) это новый код.

2024-12-10 23:17 UTC, nixel2007 commented on src/OneScript.Web.Server/HttpRequestWrapper.cs
> +                    return BslNullValue.Instance;
А, ты конкретно про пакет веб-сервера, ок

2024-12-13 16:49 UTC, EvilBeaver commented
@akpaevj LGTM. Вливать?

2024-12-13 16:51 UTC, akpaevj commented
Да

2024-12-13 17:07 UTC, merged