Добавлен и реализован объект ЧтениеJSON
EvilBeaver/OneScript pull request #360
Opened 2016-11-10 19:01 UTC by alexkmbk

Добавлен и реализован объект ЧтениеJSON с использованием фреймворка Newtonsoft.Json
Добавлено перечисление ТипЗначенияJSON
Добавлены тесты

Нерешенные проблемы:
Значения свойств ТекущаяСтрока и ТекущаяПозиция в некоторых случаях отличаются от значений, которые выдаются платформой 1С: Предприятие на том же самом Json тексте. Пока сильно с этим не разбирался, поскольку эти свойства кажутся не очень критичными для функционала.

2016-11-10 19:20 UTC, alexkmbk commented
Проверял работу под Ubuntu 14 - работает.

2016-11-10 19:25 UTC, nixel2007 commented
Боюсь быть сожженным на костре, но спрошу. 

А чтение объекта целиком планируется? Не последовательным чтением, а сразу всю структуру в память?

2016-11-10 19:26 UTC, dmpas commented
На заметку.
@alexkmbk можно своё хранилище подключить к AppVeyor и Travis - настройки для этого есть. Тогда "проверял работу под (ubuntu, windows, osx)" будет тестироваться автоматически при коммите и будет видно другим.

2016-11-10 19:41 UTC, alexkmbk commented
> можно своё хранилище подключить к AppVeyor и Travis    
Как нибудь надо будет посмотреть.
>А чтение объекта целиком планируется?    
Ну я не планировал :-)
Думаю что частично можно это поведение реализовать посредством чтения всего файла в строку и последующей передачей её в метод УстановитьСтроку(), тогда будет обработана вся строка целиком.

Фреймворк от Newtonsoft изначально заточен под работу с поточным чтением, и я подумал что наверное хорошо следовать этой методологии. Главный плюс вижу в безопасности, например, если пользователь вместо json, по ошибке укажет скажем путь к видеофайлу, придется его целиком загрузить в память и если мы еще к тому моменту не упадем, выяснить что это не тот файл.
На счет записи в этом плане еще не думал, там думаю что стримы не так актуальны.

2016-11-11 04:24 UTC, alexkmbk commented
Я честно сказать так и не осилил работу с перечислениями в движке, поэтому делаю тупо по шаблону. И вот сейчас вылез такой нюанс, на значении Null перечисления ТипЗначенияJSON, движком выдается ошибка "Ожидается идентификатор" если обращаться через точку: ТипЗначенияJSON.Null

если же обращаться через квадратные скобки, т.е. ТипЗначенияJSON.["Null"] то все работает.
С прочими значениями этого перечисления такой проблемы нет. Я было подумал что это  из-за того что  не задан alias для него,  но нет, ошибка есть в любом случае.

2016-11-11 05:03 UTC, dmpas commented
@alexkmbk с перечислениями с недавних пор стало гораздо проще. Можно посмотреть, как сделан СтатусСообщения.

2016-11-11 05:23 UTC, alexkmbk commented
@dmpas 100% проблема в самом наименовании Null, если изменить name, то ошибка исчезает.

2016-11-11 05:26 UTC, alexkmbk commented
Да уж, мой коммит состоит из 666 новых строк. В Китае цифра 6 является счастливым числом )))

2016-11-11 05:44 UTC, dmpas commented
@alexkmbk а если сделать `NULL` большими буквами? В скрипте-то без разницы будет.

2016-11-11 06:09 UTC, alexkmbk commented
@dmpas Изменение регистра не помогает.

2016-11-11 08:21 UTC, EvilBeaver commented
@dmpas, @alexkmbk по идее, это ошибка компилятора. Хотя, это, ЕМНИП, фиксили давным-давно, видимо Null пропустили. Исправлю. До исправления сливать этот пулреквест не буду пока.

2016-11-11 17:25 UTC, artbear commented on tests/json/test_json.os
> +Инициализация();
Сделай перенос на новую строку, чтобы гит и гитхаб корректно обрабатывали текущую строку

2016-11-11 17:27 UTC, artbear requested changes

2016-11-11 17:27 UTC, artbear commented on tests/json/test_json.os
> +	Пока Чтение.Прочитать() Цикл
Предлагаю отрефакторить код тестов.
Сейчас 2 теста с вычислением хеша сильно дублируют друг друга - цикл чтения и цикл преобразования в строку.

2016-11-11 17:28 UTC, artbear requested changes

2016-11-11 17:28 UTC, artbear commented on tests/json/test_json.os
> +	джейсон = "{
ИМХО идет дублирование тестовой фикстуры в файле *.json и коде теста - текст очень похож.
Предлагаю устранить дублирование

2016-11-11 18:03 UTC, alexkmbk commented on tests/json/test_json.os
> +	Пока Чтение.Прочитать() Цикл
Согласен, тоже думал над этим, только цикл чтения все таки отличается, там в одном случае добавляется функция Пропустить в нескольких местах, поэтому вынести часть логики оттуда в общую функцию проблематично, а вот получение хеша легко вынести.

2016-11-11 18:03 UTC, alexkmbk commented on tests/json/test_json.os
> +	джейсон = "{
согласен

2016-11-11 18:38 UTC, alexkmbk commented
@artbear поправил как смог, надеюсь пройти ОТК ))

2016-11-13 19:21 UTC, artbear requested changes

2016-11-13 19:21 UTC, artbear commented on tests/json/test_json.os
> +Процедура Инициализация()
Пустой метод Инициализация предлагаю удалить

2016-11-13 19:27 UTC, artbear requested changes

2016-11-13 19:27 UTC, artbear commented on tests/json/test.json
> +}
Опять завершение файла на значимой строке.
Добавь пустую строку в конец файла.

2016-11-13 19:27 UTC, artbear commented on src/ScriptEngine.HostedScript/Library/Json/JSONValueTypeEnum.cs
> +}
Опять завершение файла на значимой строке.
Добавь пустую строку в конец файла.

2016-11-13 19:27 UTC, artbear commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +}
Опять завершение файла на значимой строке.
Добавь пустую строку в конец файла.

2016-11-13 19:29 UTC, artbear commented on tests/json/test_json.os
> +	Пока Чтение.Прочитать() Цикл
Мне все-таки не нравится наличие почти одинаковых довольно длинных циклов обработки чтения.
Предложил бы добавить параметризованный метод, где параметр отвечает за пропуск чтения.
Но сильно настаивать не буду :)

2016-11-13 19:39 UTC, artbear reviewed
Больше дополнений у меня нет

2016-11-13 20:16 UTC, EvilBeaver requested changes
Больше замечаний нет. Жду мнения автора по вопросам.

2016-11-13 20:16 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +        private StringReader _stringReader; // Используется, если json текст задан с помощью функции "УстановитьСтрока"
Неясно для чего используются 2 отдельных ридера. По идее, они оба наследники StreamReader и можно обойтись одним. Нет?

2016-11-13 20:16 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +                        throw new Exception("Ошибка при получении значения атрибута контекста (ТекущееЗначение): Текущее значение JSON не может быть получено");
1C себя так же ведет и такой же текст выдает? В любом случае, нужно использовать RuntimeException вместо обобщенного Exception.

2016-11-13 20:16 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +                    throw new Exception("Источник данных JSON не открыт");
Аналогично с типом исключения.

2016-11-13 20:16 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +            if (_fileReader != null)
А если из строки открывали, то будет другой ридер, нет? Почему я и говорю, что лучше использовать один абстрактный StreamReader.

И второе, я бы упростил данный код вот так:

```C#
if(IsOpen())
{
    _reader.Dispose();
    _streamReader.Dispose();
    _reader = null;
    _streamReader = null;
}
```

Т.е. проверка на null в данном случае уже реализована в IsOpen(). А код более "говорящий" получается.

2016-11-13 20:16 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +            if (_fileReader != null)
Лучше так:

    if(IsOpen()) 
         Close();

2016-11-13 20:16 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +            _stringReader = null;
И опять мучаемся с двумя ридерами. Кстати, пришла мысль, а вообще эти ридеры нужны сами по себе, глобально? Или единственное место, где они нужны - это вот здесь, передача в JsonTextReader? Если да, то на уровне класса вообще переменную надо убрать, она спокойно будет жить внутри объекта json, а нам не надо будет ей управлять. Управлять будем только жизнью JsonTextReader.

2016-11-14 04:29 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +        private StringReader _stringReader; // Используется, если json текст задан с помощью функции "УстановитьСтрока"
Наверное это недостаток моих знаний, но я не вижу как просто можно использовать потоковое чтение одного типа и для чтения строки и для чтения файла, ведь специально для этих целей было создано два разных класса: StringReader и StreamReader. Можно было бы создавать объект String из строки и передавать в StreamReader, но раз есть уже готовый класс для чтения строки, мне показалось так правильнее.

2016-11-14 04:38 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +                        throw new Exception("Ошибка при получении значения атрибута контекста (ТекущееЗначение): Текущее значение JSON не может быть получено");
Да, генерируется исключение, прилагаю скриншот с ошибкой:
![image](https://cloud.githubusercontent.com/assets/8283410/20253529/684bcff2-aa56-11e6-9c86-47d4c532a2be.png)

2016-11-14 04:39 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +                    throw new Exception("Источник данных JSON не открыт");
Исправлю на RuntimeException

2016-11-14 04:47 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +            _stringReader = null;
Опять же, думаю недостаток моих знаний сказывается. Тут у меня появились сомнения относительно того, как работает метод Close у класса JsonTextReader, вызывает ли он метод Dispose у переданного в конструктор объекта StreamReader? В документации ничего не сказано, возможно в мире .NET это подразумевается само собой, не знаю.
Также у метода JsonTextReader нет открытого метода Dispose. Таким образом я возжелал (может быть совершенно напрасно) явно вызвать в методе Закрыть метод Dispose у объекта StreamReade. По этой причине и вынес его  в область видимости класса JSONReader.

2016-11-14 06:35 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +            _stringReader = null;
По изучаю вопрос, для лучшего понимания что происходит, надо посмотреть исходники.

2016-11-14 08:08 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +        private StringReader _stringReader; // Используется, если json текст задан с помощью функции "УстановитьСтрока"
Там три класса. базовый StreamReader и два наследника: StringReader и FileReader. Так вот, нам нужен первый, представляющий читатель абстрактного потока. Нам пофиг из файла или из строки. Конкретный экземпляр создаем в методе "Открыть" или "УстановитьСтроку". ООП жеж в чистом виде.

``` C#
private StreamReader _dataReader;

public void OpenFile()
{
   _dataReader = new FileReader(...);
}

public void SetString()
{
   _dataReader = new StringReader(...);
}
```

как-то так. А методы у них у всех одинаковые, использование стало быть, тоже одинаковое, независимо от типа.

2016-11-14 08:09 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +                        throw new Exception("Ошибка при получении значения атрибута контекста (ТекущееЗначение): Текущее значение JSON не может быть получено");
Ок, отлично.

2016-11-14 08:10 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +            _stringReader = null;
Традиционно, владеющий объект закрывает свой нижележащий Stream. Но это лишь соглашение, гарантий нет. Поэтому, можно и оставить два объекта, не страшно.

2016-11-14 08:48 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +        private StringReader _stringReader; // Используется, если json текст задан с помощью функции "УстановитьСтрока"
И то верно, согласен, только абстрактный класс там не StreamReader (он как раз с файлами работает), а TextReader.
Однако решил отказаться от этих переменных класса, вместо этого, буду вызывать в методе Закрыть метод Close класса JsonTextReader. Посмотрел в его исходники, там вызывается метод Close у переданного объекта чтения + еще добавлю вызов метода Close в финализатор класса JSONReader дабы очистить неуправляемые ресурсы если это не было сделано явно.

2016-11-14 08:50 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Json/JSONValueTypeEnum.cs
> +}
Исправлю, только я пока не понимаю чем это плохо, имхо чувствую какую-то неправильность в этом.

2016-11-14 08:56 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONValueTypeEnum.cs
> +}
Мне тоже интересно зачем это...

2016-11-14 08:59 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +        private StringReader _stringReader; // Используется, если json текст задан с помощью функции "УстановитьСтрока"
Вот в финализатор не надо. Это очень тонкая штука и редко нужная. В JSONReader **нет** неуправляемых ресурсов. Только управляемые.

2016-11-14 13:36 UTC, EvilBeaver approved these changes

2016-11-14 13:36 UTC, merged