[WIP] Статистика выполнения кода
EvilBeaver/OneScript pull request #374
Opened 2016-12-13 10:29 UTC by dmpas

* Добавлен ключ `-codestat=<filename>`
 * Подсчёт строк приведён в соответствие с поведением Родительской Платформы. В качестве побочного явления - обилие LineNum в байткоде.
 * Подсчёт количества проходов и времени выполнения.

2016-12-13 10:30 UTC, dmpas commented
@nixel2007 с тебя тесты.

2016-12-13 10:40 UTC, nixel2007 commented on tests/codestat.os
> +	Если Чтение.ТипТекущегоЗначения = ТипЗначенияJson.НачалоОбъекта Тогда
Я буду еретиком, если спрошу можно ли перевести с встроенного потокового чтения на библиотеку json, которая сразу объект вернет? :(

2016-12-13 10:43 UTC, artbear requested changes

2016-12-13 10:43 UTC, artbear commented on tests/codestat.os
> +	ИмяФайлаОСкрипта = ПолучитьИмяВременногоФайла("os");
Временные файлы специально не удаляются?
Предлагаю добавить их удаление в ПослеЗапускаТеста или использовать пакет ВременныеФайлы

2016-12-13 10:43 UTC, artbear commented on tests/codestat.os
> +		Возврат Неопределено;
Предлагаю сразу выбрасывать исключение

2016-12-13 10:44 UTC, artbear commented on tests/codestat.os
> +	Если Чтение.ТипТекущегоЗначения = ТипЗначенияJson.НачалоОбъекта Тогда
У меня был этот же вопрос.
Почему-то @dmpas не юзает библиотеки :(

2016-12-13 10:50 UTC, dmpas commented on tests/codestat.os
> +	Если Чтение.ТипТекущегоЗначения = ТипЗначенияJson.НачалоОбъекта Тогда
Просто не хочется завязывать тестирование движка на библиотеки. А так, религия не запрещает.

2016-12-13 10:50 UTC, dmpas commented on tests/codestat.os
> +	ИмяФайлаОСкрипта = ПолучитьИмяВременногоФайла("os");
Принято.

2016-12-13 10:51 UTC, dmpas commented on tests/codestat.os
> +		Возврат Неопределено;
Принято.

2016-12-16 13:20 UTC, nixel2007 commented
@dmpas правильно понимаю, что новый тест теперь - просто новый os файлик в папке?
👍

2016-12-16 13:21 UTC, dmpas commented
@nixel2007 да, только разметить его надо соответствующим образом.

2016-12-16 13:49 UTC, nixel2007 commented
while.os
```bsl
Пока Истина Цикл     //- $entry: 1
	А = 0;           //- $entry: 1
	Прервать;        //- $entry: 1
	Б = 0;           //- $entry: 0
КонецЦикла;          //- $entry: 1

Для сч = 1 По 2 Цикл //- $entry: 3
	А = 0;           //- $entry: 2
КонецЦикла;          //- $entry: 3
```

try.os
```bsl
Попытка             //- $entry: 1
	А = 0;          //- $entry: 1
Исключение          //- $entry: 0
	Б = 0;          //- $entry: 0
КонецПопытки;       //- $entry: 1

Попытка             //- $entry: 1
	А = Число("ы"); //- $entry: 1
Исключение          //- $entry: 1
	Б = 0;          //- $entry: 1
КонецПопытки;       //- $entry: 1
```

2016-12-16 13:54 UTC, dmpas commented
@nixel2007 ты можешь всё тот же артефакт с аппвеёра качать.

2016-12-18 12:58 UTC, dmpas commented
@nixel2007 после "Прервать" КонецЦикла не выполняется. Ни у нас, ни в Жёлтой Маме. Потому, там будет 0.

2016-12-19 10:30 UTC, EvilBeaver commented on src/ScriptEngine/Compiler/Parser.cs
> +                            LineNumber = currentLine
ой-вей... а оно точно надо в лексему номер строки добавлять?

2016-12-19 10:30 UTC, EvilBeaver commented on src/ScriptEngine/Compiler/SourceCodeIndexer.cs
> +        private readonly IDictionary<int, int> _lineBounds;
А как будет работать данный словарь? Чем старый вариант не угодил?

2016-12-19 10:30 UTC, EvilBeaver commented on src/ScriptEngine/Compiler/Compiler.cs
> +            var loopBegin = AddCommand(OperationCode.LineNum, _lastExtractedLexem.LineNumber);
Я немного потерялся в вашей дискуссии с @nixel2007. Если я правильно понял, то есть цель учитывать выполнение строк КонецЦикла и т.п?

Изначально опкод LineNumber использовался только для выдачи корректных рантайм исключений. Я верно понимаю, что сейчас предлагается его использовать еще и для статистики кода?

2016-12-19 10:42 UTC, dmpas commented on src/ScriptEngine/Compiler/Compiler.cs
> +            var loopBegin = AddCommand(OperationCode.LineNum, _lastExtractedLexem.LineNumber);
Да, верно. Сейчас порядок выполнения опкодов LineNumber совпадает с тем, как в 1С отладчик по шагам проходит.

2016-12-19 10:45 UTC, dmpas commented on src/ScriptEngine/Compiler/Parser.cs
> +                            LineNumber = currentLine
Да, так гораздо проще. Потому что парсер после лексемы мог убежать уже куда угодно и слишком много пришлось бы тогда пилить в парсере. А тут просто запомнил, где встретилась лексема, и всё.

2016-12-19 10:47 UTC, dmpas commented on src/ScriptEngine/Compiler/SourceCodeIndexer.cs
> +        private readonly IDictionary<int, int> _lineBounds;
Разница при MoveBack/MoveNext. В List делался Add, что вообще не гарантировало, что нужная строка окажется именно по тому индексу, который ей соответствует. Лучше всего это ловилось на случаях, когда файл начинается с пустой строки - она вообще выпадала из анализа.
А в словаре в этом отношении всё однозначно.

2016-12-21 10:40 UTC, dmpas commented
@nixel2007 напомню про тесты, а то у меня под новый год будет затык со временем.

2016-12-21 11:39 UTC, nixel2007 commented
@dmpas я если честно не знаю, что ещё можно добавить. Вызовы функций есть, циклы, попытки, если есть.

2016-12-21 11:55 UTC, artbear commented
Рекурсию считали?

2016-12-21 11:58 UTC, artbear commented
+ Пока цикл
+ Для по Цикл
+ Для каждого Цикл
+ Если Тогда Иначе
+ Оператор ? как будет учтен?
+ (Новый Объект).ВызовМетода ?
+ Процедура/функция?

2016-12-23 11:23 UTC, nixel2007 commented
@dmpas не могу понять, как запустить отдельно тест codestat.os
пишу `testrunner tests\codestat.os`, кладу новый файлик в папку с тестами
new.os
```bsl
А = Новый ТаблицаЗначений();           //- $entry: 1
Б = Новый ("ТаблицаЗначений");         //- $entry: 1

В = (Новый ТаблицаЗначений()).Колонки //- $entry: 1
	.Количество(); //- $entry: 1
```

независимо от цифр тестраннер всегда выдает зеленую полосу. запуск `oscript tests\testrunner.os tests\codestat.os` так же не приносит желаемого эффекта.
Что делаю не так?

2016-12-23 11:28 UTC, dmpas commented
@nixel2007 
```
testrunner -run codestat.os
```
так попробуй

2016-12-23 11:30 UTC, artbear commented
>не могу понять, как запустить отдельно тест codestat.os
пишу testrunner tests\codestat.os, кладу новый файлик в папку с тестами

@nixel2007 А доку почитать? :) или хотя бы хелп из командной строки?

2016-12-23 11:30 UTC, dmpas commented
@nixel2007 
```bsl
В = (Новый ТаблицаЗначений()).Колонки //- $entry: 1
	.Количество(); //- $entry: 1
```
тут сейчас, к сожалению (или радости) будет "1" и "0". Многострочные выражения что у нас, что в Жёлтой Маме всегда относятся на первую строку.

2016-12-23 11:44 UTC, nixel2007 commented
> тут сейчас, к сожалению (или радости) будет "1" и "0". Многострочные выражения что у нас, что в Жёлтой Маме всегда относятся на первую строку.

В "Жёлтой Маме" ( ахахахахха ) есть хитрость.
```bsl
МояФункция(            //- $entry: 1
    Истина,                  //- $entry: 0
    Истина,                  //- $entry: 0
    ДругаяФункция(),  //- $entry: 1
    Истина                   //- $entry: 0
);                                 //- $entry: 0
```

2016-12-23 11:45 UTC, nixel2007 commented
> testrunner -run codestat.os
так попробуй

получилось без -run. Оказывается, был важен CWD - нужно быть в tests

2016-12-23 11:51 UTC, dmpas commented
@nixel2007 
```bsl
  ДругаяФункция(),  //- $entry: 1
```
вот эту хитрость я, пожалуй, отработаю всё-таки.

2016-12-23 11:57 UTC, nixel2007 commented
@dmpas обрати внимание

![image](https://cloud.githubusercontent.com/assets/1132840/21453432/0087a7b8-c920-11e6-87bf-54d023b6245b.png)

В первом запуске вместо МояФункция() была платформенная СтрШаблон() --- замер не отметился на этой строке. А вот на собственной функции - отметился

2016-12-28 17:50 UTC, dmpas commented
Снял WIP. 15-ю версию выпустили, 16-я далеко, можно ломать ночники :smiley:

2017-01-12 15:32 UTC, merged