Рефлектор: ПолучитьТаблицуСвойств()
EvilBeaver/OneScript pull request #428
Opened 2017-05-02 10:05 UTC by ret-Phoenix

Получает таблицу свойств для переданного объекта.
Возвращает: Таблица значений с 1 колонкой - Имя

2017-05-02 10:19 UTC, ret-Phoenix commented
#178 Ранее был реализован только метод ПолучитьТаблицуМетодов

2017-05-02 11:32 UTC, EvilBeaver commented
А почему не Массив, раз всего одна колонка? Или сделать еще колонки CanRead CanWrite?

2017-05-02 11:44 UTC, ret-Phoenix commented
Потом хочу расширить колонки, после доработки по Геттерам и Сеттерам.

2017-05-02 11:48 UTC, ret-Phoenix commented
Определить CanRead + CanWrite не уверен что получится.

2017-05-02 14:43 UTC, artbear requested changes

2017-05-02 14:43 UTC, artbear commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(2, ТаблицаСвойств.Количество());
Почему количество 2? ведь всего одна экспортная переменная в коде?

2017-05-02 14:51 UTC, ret-Phoenix commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(2, ТаблицаСвойств.Количество());
Автоматически добавляется переменная ЭтотОбъект

2017-05-02 14:55 UTC, artbear commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(2, ТаблицаСвойств.Количество());
Зачем добавляется?
ИМХО получаем расхождение с кодом модуля.
Зачем заклывать эту мину?

2017-05-02 14:57 UTC, ret-Phoenix commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(2, ТаблицаСвойств.Количество());
Таково поведение движка. при создании объекта добавляется "служебное"  свойство "ЭтотОбъект". Можно его игнорировать, для этого добавить условие в цикле

2017-05-02 15:02 UTC, artbear commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(2, ТаблицаСвойств.Количество());
ИМХО нужно игнорить.
Зачем мне как пользователю рефлектора помнить об этом доп.свойстве?

@EvilBeaver @dmpas что скажете?

2017-05-02 16:40 UTC, dmpas commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(2, ТаблицаСвойств.Количество());
нужно игнорить. в других языках ведь не находится свойство "this" :)

2017-05-02 16:44 UTC, dmpas commented on tests/reflector.os
> +	юТест.ПроверитьРавенство(2, ТаблицаСвойств.Количество());
Сразу ещё тогда "ThisObject" обрабатывай. Его хоть и нет сейчас, но руки чешутся добавить  :)

2017-05-03 13:02 UTC, EvilBeaver approved these changes

2017-05-03 13:02 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Reflector.cs
> +            var NameColumn = Result.Columns.Add("Имя", ValueFactory.Create(""), "Имя"); // TODO: Доработать после увеличения предела количества параметров
Что означает этот TODO? Что нужно сделать по нему?

2017-05-03 13:02 UTC, EvilBeaver commented on src/ScriptEngine/Machine/IRuntimeContextInstance.cs
> +        IEnumerable<VariableInfo> GetProperties();
Блин, все это породит конфликты при вливании отладчика. Там по свойствам очень много переделано... Ладно, пусть пока так остается.

2017-05-03 13:04 UTC, merged