Feature/from sys info to global context
EvilBeaver/OneScript pull request #430
Opened 2017-05-04 13:02 UTC by ret-Phoenix

#426

2017-05-04 17:00 UTC, EvilBeaver requested changes

2017-05-04 17:00 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemEnvironmentContext.cs
> +            System.Console.WriteLine("DeprecationWarning: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context");
Есть специальный лог для этого. Поищи в компиляторе по слову except

2017-05-04 17:00 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            _systemEnvironmentContext = new SystemEnvironmentContext();
Глоб контекст делается не так. См. Метод КопироватьФайл, СтрНайти и пр.

2017-05-05 08:32 UTC, ret-Phoenix commented on src/ScriptEngine.HostedScript/Library/SystemEnvironmentContext.cs
> +            System.Console.WriteLine("DeprecationWarning: 'SystemInfo.GetEnvironmentVariable' is deprecated, use 'GetEnvironmentVariable' from global context");
Спасибо, нашел как сделать.

2017-05-05 08:33 UTC, ret-Phoenix commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            _systemEnvironmentContext = new SystemEnvironmentContext();
Не понял, чем не устраивает?
фактически я вызываю методы из существующего класса, чтобы не дублировать.

2017-05-09 07:27 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs
> +            _systemEnvironmentContext = new SystemEnvironmentContext();
Это не дублирование. Вот этот класс он немного про другое и вообще просится на рефакторинг. Не надо его развивать

2017-05-12 08:34 UTC, EvilBeaver commented
@ret-Phoenix влить не могу, т.к. есть конфликты. Просьба разрулить.

2017-05-12 09:35 UTC, ret-Phoenix commented
Прав у меня нет, но я добавлял, а потом убирал только 1 строку: 
`_systemEnvironmentContext = new SystemEnvironmentContext();`
Она не нужна
`
RegisterProperty("Символы", () => (IValue)Chars);
RegisterProperty("Chars", () => (IValue)Chars);
`
Это Серега наверное пилил

2017-05-12 10:38 UTC, nixel2007 commented
@ret-Phoenix 
> Прав у меня нет

дык мерж-то можно локально сделать. Мерж EvilBeaver/master в твою ветку и пуш в твою ветку.

2017-05-15 14:54 UTC, merged