Конструктор скрипт-классов с параметрами
EvilBeaver/OneScript pull request #443
Opened 2017-05-23 13:42 UTC by ret-Phoenix

Реализацию деструктора выкладывать не стал.
По Конструктору скорее всего будут замечания по стилистике.

2017-05-24 07:19 UTC, EvilBeaver requested changes

2017-05-24 07:19 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +        public IValue[] ConstructorParams { get { return constructorParams; } set { constructorParams = value; } }
Для этого лучше использовать автосвойства C# 6:

    public IValue[] ConstructorParams { get; set; } = new IValue[0];

И лишняя переменная будет не нужна.

2017-05-24 07:19 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +        //~ScriptDrivenObject()
Это не деструктор. Все объектные переменные в момент его вызова могут уже быть собраны сборщиком мусора. Вытаскивать в язык - чревато.

Правильный деструктор - через счетчик ссылок.

2017-05-24 07:19 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +            var methId = GetScriptMethod("конструктор", "constructor");
Предложение. Назвать волшебный метод не "Конструктор", а "ПриСозданииОбъекта" или "ОбработкаСозданияОбъекта"

2017-05-24 07:40 UTC, ret-Phoenix commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +        public IValue[] ConstructorParams { get { return constructorParams; } set { constructorParams = value; } }
По мимо этого, а стоило ли конструктор переделывать? может все же лучше было через public свойство, до вызова инициализации прописать, но вариант передачи через конструктор надежней, как мне кажется. не получится такого, что не в том порядке вызвал и облом.

2017-05-24 07:41 UTC, ret-Phoenix commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +        //~ScriptDrivenObject()
Поэтому и отключил, а вот код надо было убрать ...

2017-05-24 07:42 UTC, ret-Phoenix commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +            var methId = GetScriptMethod("конструктор", "constructor");
Почему? чтобы метод назывался максимально в стиле 1С или из-за возможных проблем с ранее написанным кодом, где мог быть метод Конструктор?

2017-05-24 07:47 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +            var methId = GetScriptMethod("конструктор", "constructor");
Во-первых, чтобы было в стиле 1С. Во-вторых, сначала все равно будет выполняться код из тела модуля внизу, а этот метод он не конструктор уже, в таком случае, а обработчик инициализации.

2017-05-25 09:27 UTC, artbear commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +            var methId = GetScriptMethod("конструктор", "constructor");
Не согласен. ИМХО имя "Конструктор" очень четко говорит о цели функции, а вот "ПриСозданииОбъекта" или "ОбработкаСозданияОбъекта" слишком многобуквенны и запутывают.

2017-05-25 09:28 UTC, artbear commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +        //~ScriptDrivenObject()
>Правильный деструктор - через счетчик ссылок.

@EvilBeaver @dmpas А есть примеры счетчика ссылок в проекте?

2017-05-25 09:32 UTC, artbear requested changes
Небольшие правки

2017-05-25 09:32 UTC, artbear commented on tests/constructor.os
> +		Ожидаем.Что(ОписаниеОшибки()).Содержит("Конструктор не определен");
А вот этот тест зачем?
Наличие конструктора - это не обязательная опция!
Тест неверен

2017-05-25 09:32 UTC, artbear commented on tests/constructor.os
> +		Ожидаем.Что(ОписаниеОшибки()).Содержит("Конструктор не определен");
Точнее, лучше так - тест верен и проверяет отсутствие конструктора.
Просто нужен еще один тест, который проверяет создание объекта `Новый ПроверкаБезКонструктора` для проверки факта необязательности конструктора

2017-05-25 09:32 UTC, artbear commented on tests/constructor.os
> +#Использовать logos
зачем в этом тесте logos?

2017-05-25 09:35 UTC, nixel2007 commented on tests/constructor.os
> +		Ожидаем.Что(ОписаниеОшибки()).Содержит("Конструктор не определен");
> Наличие конструктора - это не обязательная опция!

обязательная, если конструктору передаются параметры

2017-05-25 09:38 UTC, artbear commented on tests/constructor.os
> +		Ожидаем.Что(ОписаниеОшибки()).Содержит("Конструктор не определен");
Поэтому выше я и предложил дополнить тесты

2017-05-25 09:42 UTC, ret-Phoenix commented on tests/constructor.os
> +		Ожидаем.Что(ОписаниеОшибки()).Содержит("Конструктор не определен");
есть метод в тесте
`
Процедура ТестДолжен_СоздатьОбъектЛог() Экспорт
	
	НовыйОбъект = Новый Лог();
	
КонецПроцедуры
`

2017-06-07 13:43 UTC, EvilBeaver commented
@ret-Phoenix как-то тема заглохла... Внесешь правки?

2017-06-08 06:41 UTC, ret-Phoenix commented
Давай определимся с названием метода.
В стиле 1С: ПриСозданииОбъекта - меня вполне устроит.
Если ок - на выходных постараюсь сделать заливку сразу 2-3 PR

2017-06-16 08:30 UTC, ret-Phoenix commented
Ушло в пользу: https://github.com/EvilBeaver/OneScript/pull/455

2017-06-16 14:24 UTC, closed without merging