Магия, расширение Системной информации, информация о диске, сигнал
EvilBeaver/OneScript pull request #455
Opened 2017-06-16 08:27 UTC by ret-Phoenix

- #256 - Конструктор. Обработка магического метода "ПриСозданииОбъекта", "OnObjectCreate"
- #441 - Расширение возможностей СистемнаяИнформация
- #439 - Информация о дисках
- #440 - Сигнал

2017-06-16 14:40 UTC, EvilBeaver requested changes
Просьба отработать замечания: исправить или опровергнуть.

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/ConsoleContext.cs
> +            System.Media.SystemSounds.Beep.Play();
Кажется, что здесь должен быть вот этот метод https://msdn.microsoft.com/ru-ru/library/4fe3hdb1(v=vs.110).aspx

    Console.Beep()

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("Доступно")]
1. Нет англоязычного синонима
2. Кажется, что "Доступно" не очень хорошо отражает смысл свойства. Неясно, что именно доступно. Может "ДоступноеПространство" или "СвободноеМесто"?

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("ИмяФС")]
Нет англоязычного синонима

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("Готов")]
Англ?

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("Имя")]
Англ?

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("КорневойКаталог")]
Англ?

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("ОбщийОбъемСвободногоМеста")]
А как это пересекается с "Доступно"? Это разные показатели?

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SpecialFolderEnum.cs
> +    public enum SpecialFolder
Кажется что этот энум лишний, нет? Его же вполне заменяет родной .NET-овский.

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +        //~ScriptDrivenObject()
Забыли удалить коментированный код.

2017-06-16 14:40 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemEnvironmentContext.cs
> +        public ArrayImpl GetLogicalDrives
Наверное, лучше FixedArrayImpl

2017-06-16 14:40 UTC, EvilBeaver commented on tests/sysinfo.os
> +	юТест.ПроверитьБольше(Си.ИменаЛогическихДисков.Количество(),0);
На линуксе отработает?

2017-06-16 14:40 UTC, EvilBeaver commented on tests/sysinfo.os
> +	юТест.ПроверитьИстину(Си.Это64БитнаяОперационнаяСистема);
Надеюсь, все переехали с x86 :))

2017-06-16 15:31 UTC, dmpas commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("ИмяФС")]
не нужны же теперь англоязычные синонимы - они берутся из самого имени.

2017-06-16 16:08 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("ИмяФС")]
Разве? Я не знал...

2017-06-16 17:11 UTC, dmpas commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("ИмяФС")]
https://github.com/EvilBeaver/OneScript/commit/c29f33f736ca42305e254ba0a1e46f34041e2f0a

2017-06-19 06:37 UTC, ret-Phoenix commented on src/ScriptEngine.HostedScript/Library/SpecialFolderEnum.cs
> +    public enum SpecialFolder
Заменяет, но сделал преднамеренно, т.к. доступны *не все* папки, брал доступное в mono.

2017-06-19 06:37 UTC, ret-Phoenix commented on tests/sysinfo.os
> +	юТест.ПроверитьИстину(Си.Это64БитнаяОперационнаяСистема);
у меня разные есть ;)

2017-06-19 06:38 UTC, ret-Phoenix commented on tests/sysinfo.os
> +	юТест.ПроверитьБольше(Си.ИменаЛогическихДисков.Количество(),0);
Серега проверял, работало. Результат теста могу поискать.

2017-06-19 07:02 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemEnvironmentContext.cs
> +            System.Console.WriteLine(folder.SystemType.Name);
А еще тут отладочный WriteLine который не нужен.
@ret-Phoenix  я взялся подправить кой-чего, если ты не возражаешь, прямо у тебя тут.

2017-06-19 08:14 UTC, ret-Phoenix commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("Доступно")]
Думаю остановиться на "ДоступноеСвободноеМесто"

2017-06-19 08:16 UTC, ret-Phoenix commented on src/ScriptEngine.HostedScript/Library/DriveInfo/DriveInfo.cs
> +        [ContextProperty("ОбщийОбъемСвободногоМеста")]
Да, разные, толком не разбирался в чем разница, но в .net это разные вещи

2017-06-19 08:21 UTC, merged