Небольшие доработки
EvilBeaver/OneScript pull request #502
Opened 2017-08-09 11:21 UTC by dmpas

2017-08-09 11:51 UTC, artbear requested changes

2017-08-09 11:51 UTC, artbear commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
что за извращения??
Платформа 1С накосячила с именем, теперь и мы будет неверное имя юзать ??
Предлагаю оставить оба варианта и ElseIf и ElsIf

2017-08-09 11:57 UTC, dmpas commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
Вот признайся, сколько раз в твоём коде встречалось слово `ElseIf`, а сколько `ElsIf` ? и сколько раз `ИначеЕсли`? `ElsIf` - это не косяк 1С, оно много где используется именно в таком виде

2017-08-09 12:50 UTC, artbear commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
Мы пишем именно ИначеЕсли, а не ИначЕсли :)
язык 1С "произошел" от Basic, а там как раз юзается Else IF

2017-08-09 12:55 UTC, dmpas commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
> Мы пишем именно ИначеЕсли
> теперь и мы будет неверное имя юзать ??

вот как не юзали басурманское слово, так и не будем юзать. А в остальном следует придерживаться совместимости.

2017-08-09 13:04 UTC, Faithfinder commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
Баба яга хочет сказать что поддерживать оба варианта звучит оптимально - и совместимость поддерживается, и те кто не догадается курить маны в поисках особенностей, а пишет правильный перевод на отвалится.

2017-08-09 13:09 UTC, dmpas commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
Вот пишешь ты себе в коде `ElseIf`, потом переносишь куски в 1С, а там бац и не работает... Обидно будет, и переписывать много.

2017-08-09 13:38 UTC, artbear commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
Много ты видел кода, перенесенного из оскрипт в 1С :) ?

2017-08-09 13:39 UTC, dmpas commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
Да балуюсь время от времени.

2017-08-09 14:59 UTC, Faithfinder commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
Ctrl-H...

2017-08-09 15:07 UTC, dmpas commented on src/ScriptEngine/Compiler/Tokens.cs
> +                    SystemLogger.Write("English 'ElseIf' is deprecated! Use 'ElsIf' instead!");
> Ctrl-H...
зачем? если можно сразу писать совместимо. Поддерживать два разных стиля - плохо.

2017-08-09 18:32 UTC, EvilBeaver commented
Блеать, как так? ElsIf??

И так всегда было в 1С? И с ```ЗначениеЗаполнено``` тоже что случилось?

2017-08-09 18:33 UTC, EvilBeaver commented
Багфикс со структурой однозначно вливаем, по языковым доработкам - у меня есть вопросы.
Давайте разобьем на два пулреквеста

2017-08-10 05:48 UTC, dmpas commented
> И так всегда было в 1С?

@EvilBeaver проверил синтаксис-помощник в 8.2.19.130 - всё так. А это 2013 год.

2017-08-10 06:22 UTC, dmpas commented
Структуру вынес отдельно: https://github.com/EvilBeaver/OneScript/pull/504

2017-08-10 06:26 UTC, nixel2007 commented
ElsIf всегда так был. Я когда грамматику делал, тоже на это нарвался.

2017-08-10 07:22 UTC, artbear commented
Вот нахера нам ElsIf ? имхо это неверно,  граммар наци негодуют

2017-08-10 07:25 UTC, dmpas commented
@artbear дык совместимость. Вот появилась настоящая задача от настоящего человека, который переносил настоящий англоязычный код из 1С в односкрипт.

2017-08-10 07:32 UTC, artbear commented
Я и предложил совместить 2 подхода для совместимости :) - и ElsIf и ElseIf
Нафига нам поддерживать только "очень странный" ElsIf ?

2017-08-10 07:39 UTC, dmpas commented
> для совместимости

для совместимости **с чем** нужен `ElseIf` ?? Я пока что не видал кучи кода на англоязычном односкрипте.

2017-08-10 07:40 UTC, artbear commented
Ответ очевиден - для совместимости с граммарнаци :) + хорошим/нормальным стилем написания кода

2017-08-10 07:42 UTC, nixel2007 commented
нене, Артур, это реально какой-то костыль. Доля англоязычных скриптописателей близка к нулю, а корректная двусторонняя совместимость с 1с важнее ненависти к авторам BSL. 
Если бы не @vsuh, я бы предложил вообще жестко дропнуть токен ElseIf.

2017-08-10 19:44 UTC, ret-Phoenix commented
Сделать нотацию как в 1с

2017-08-10 19:58 UTC, JohnyDeath commented
Как в 1С и без ElseIf

2017-08-10 20:00 UTC, pumbaEO commented
И так и так.  А тому из 1с у которого е запала и палець надо вьірвать.

10 серп. 2017 р. 10:58 пп "Evgeny Martynenkov" <notifications@github.com>
пише:

> Как в 1С и без ElseIf
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EvilBeaver/OneScript/pull/502#issuecomment-321657142>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKIc6KkFzGGpzUlzB9edWpwaSjFwxAvks5sW2DhgaJpZM4Ox8Nf>
> .
>

2017-08-10 20:23 UTC, best-tech commented
Я за два подхода, бывает сам пишешь корректо, бываешь копипастишь, разбираться при копипасте вообще не хочется, потому что смысл копипаста теряется, а вообще для конструкций хороши бы алиасы придумать, что бы потом из схожих язиков интерпретатор сделать)

2017-08-11 03:05 UTC, awa15 commented
В 1С всегда было elsif, и в семерке, и в восьмерку перекочевало. И никогда не было elseif. Все, кому кажется, что elseif - это правильно, просто не пишут на "английском 1С". Те же кто пишет, прекрасно знают, что надо писать elsif. Мое мнение - выпилить полностью elseif, оставить только правильный elsif.

2017-08-11 06:48 UTC, EvilBeaver commented
Мы уже проходили это с Except/Exception и сейчас так же поступим. Обьявляем ElseIf как deprecated а позже выпиливаем

2017-08-11 08:22 UTC, asosnoviy commented
Те кто пишут в 1с на английском, те пишут `ElsIf`. Соответственно и в односкрипте будут писать `ElsIf`. Плюсую за совместимость с 1с.

2017-08-12 19:46 UTC, EvilBeaver commented
Тогда сие закрываем, раз бьем на несколько. По Структуре смержил. По английскому элсыфу - пусть будет отдельный PR и обсуждение.

2017-08-12 19:46 UTC, closed without merging