Http classes
EvilBeaver/OneScript pull request #597
Opened 2017-11-22 16:22 UTC by jdeshin

Изменены классы HTTPRequest, HTTPResponse, HTTPConnection в части работы с телом.
На основании: https://github.com/EvilBeaver/OneScript/issues/590
Мне кажется, что так немного проще.
Относительно вопроса про поведение 1С.
Если мы записываем результаты в файл, то методы ПолучитьТелоКакСтроку, ПолучитьТелоКакДвоичныеДанные возвращают неопределено.
Метод ПолучитьТелоКакПоток возвращает поток, связанный с файлом.
Если мы получаем ответ в памяти, то ПолучитьИмяФайлаТела возвращает Неопределено, все остальные возвращают.

2017-11-22 18:01 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Http/HttpRequestBodyBinary.cs
> -This Source Code Form is subject to the terms of the
Я так и не понял, зачем вместо этого интерфейса применено постоянное сравнивание и приведение типов. Так совсем не по ООП-шному. Есть объективные причины для этого?

2017-11-22 18:01 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Http/HttpRequestContext.cs
> +            if ((_bodyStream == null) || (_bodyStream as System.IO.FileStream) == null)
Собственно, вот эта сложная логика и была спрятана внутрь полиморфных классов, чтобы жить там и наружу не вылезать. Мне не нравятся эти изменения, хотя, допускаю, что так лучше и я неправ. @dmpas что думаешь?

2017-11-22 18:01 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Http/HttpResponseBody.cs
> -﻿/*----------------------------------------------------------
Почему удален файл? Он реально не нужен? Почему? Что его заменяет?

2017-11-22 18:51 UTC, jdeshin commented on src/ScriptEngine.HostedScript/Library/Http/HttpResponseBody.cs
> -﻿/*----------------------------------------------------------
Его заменяют filename и _bodyStream. Собственно объекты то простые либо MemoryStream  в памяти либо ПутьИмяФайла, куда тело было выгружено. Было удалено 3 файла

2017-11-22 18:54 UTC, jdeshin commented on src/ScriptEngine.HostedScript/Library/Http/HttpRequestContext.cs
> +            if ((_bodyStream == null) || (_bodyStream as System.IO.FileStream) == null)
Ну логика то несложная, мне показалось, что в данном случае проще прочитать пять строк кода, прямо в теле метода. Мне кажется, что так понятнее, однако это мой частный взгляд.

2017-11-22 19:22 UTC, jdeshin commented on src/ScriptEngine.HostedScript/Library/Http/HttpRequestBodyBinary.cs
> -This Source Code Form is subject to the terms of the
Да, наверное это не по ООПшному. Основная причина, для такого простого объекта - это простота и меньшее количество кода. httprequest, по сути, не такой сложный класс и логика у него достаточно проста. Он сдержит адрес ресурса, заголовки, а также либо тело в памяти либо путь и имя файла, откуда оно будет считано. Ну и соответственно методы доступа к ним. В исходном коде  уже 5 классов, представляющих эту сущность. Конечно методологически правильным с точки зрения ООП было бы добавить еще как минимум один, но что это даст с точки зрения простоты, понимания кода, совершенно посторонними людьми со средним интеллектом и низким уровнем программирования?

2017-11-22 19:23 UTC, jdeshin commented on src/ScriptEngine.HostedScript/Library/Http/HttpResponseBody.cs
> -﻿/*----------------------------------------------------------
Прошу меня извинить, удалил 5 файлов

2017-11-22 19:46 UTC, jdeshin commented on src/ScriptEngine.HostedScript/Library/Http/HttpRequestContext.cs
> +            if ((_bodyStream == null) || (_bodyStream as System.IO.FileStream) == null)
Вот, отчасти руководствовался таким мнением Страуструпа (возможно, что совершенно неверно руководствовался):
"Не обязывайте себя сооружать огромные иерархии классов или писать запутанный мета-код с помощью шаблонов: некоторые из самых мощных возможностей C++ очень просты. Лучший путь к написанию эффективного кода — не усложнять его без необходимости."

2017-11-22 19:57 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Http/HttpResponseBody.cs
> -﻿/*----------------------------------------------------------
Меня смущает, что я бы точно не стал городить целый сложный класс просто так. Но вот не могу вспомнить зачем я его написал. Кажется, что все не так просто...

2017-11-22 19:59 UTC, EvilBeaver commented
@dmpas, посмотри, пожалуйста, этот PR. Я как-то потерялся ((

2017-11-22 20:35 UTC, jdeshin commented on src/ScriptEngine.HostedScript/Library/Http/HttpResponseBody.cs
> -﻿/*----------------------------------------------------------
Ну я тупо создал обработку и в ней комбинировал вызовы. Если смущает будет ли работать - можно провести какие-нибудь доп тесты. Тот, кто написал запрос о добавлении функционала, наверняка плотно юзает эти штуки, да я и сам собираюсь их активно использовать. Можно попросить потестировать. Это не будет наглостью?

2017-11-22 20:43 UTC, jdeshin commented
Что-то непонятное мне. При Windows сборке. У меня на локале все норм. Сейчас сделал ребилд
java.nio.channels.ClosedChannelException

2017-11-22 20:43 UTC, jdeshin commented
Вторая строка - это ошибка

2017-11-22 20:44 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Http/HttpResponseBody.cs
> -﻿/*----------------------------------------------------------
Запрос о добавлении функционала написал мой давний друг Вовка. Можно его попросить поиспользовать, но как быстро будет результат - неизвестно )) Верно, @vbondarevsky?

2017-11-23 06:33 UTC, dmpas commented
@EvilBeaver вот он я. Ща красные трусы надену и буду смотреть.

2017-11-23 06:36 UTC, EvilBeaver commented
Красные трусы?

2017-11-23 06:46 UTC, dmpas commented
@EvilBeaver  https://yandex.ru/images/search?text=%D1%81%D1%83%D0%BF%D0%B5%D1%80%D0%BC%D0%B5%D0%BD

2017-11-23 07:55 UTC, dmpas commented
два часа красноглазил на всё это и моё мнение такое: надо вернуть абстракцию. Http-ответ/запрос не должны знать, где по факту находится тело. С телом тоже надо будет отдельно поработать напильником (уже не в рамках этой задачи), что тоже будет гораздо проще, если тело будет отдельной абстракцией.

PS двоичные данные нам надо переделать: у нас файл с диска сразу считывается, а в 1С - нет. + Размеры потоков с инта на лонг надо переделывать по-любому.

2017-11-23 07:55 UTC, dmpas requested changes
Вернуть абстракцию.

2017-11-23 08:29 UTC, jdeshin commented
Ну ОК, отменяем

2017-11-23 08:29 UTC, closed without merging

2017-11-23 21:16 UTC, vbondarevsky commented on src/ScriptEngine.HostedScript/Library/Http/HttpResponseBody.cs
> -﻿/*----------------------------------------------------------
@EvilBeaver ))) Ну будет готово, проверю

2017-11-24 07:51 UTC, jdeshin commented on src/ScriptEngine.HostedScript/Library/Http/HttpResponseBody.cs
> -﻿/*----------------------------------------------------------
Уже отменили. "Отцы" сказали не ООПэшно :)