Fix #616: параметр Монопольно в чтении текста.
EvilBeaver/OneScript pull request #618
Opened 2017-12-11 09:32 UTC by dmpas

В ЧтениеТекста в конструктор по имени файла и метод Открыть добавлен
флаг Монопольно для указания признака монопольного захвата файла.

2017-12-11 09:38 UTC, dmpas commented
@artbear проверишь сборочку на своих случаях?

2017-12-11 09:47 UTC, dmpas commented
@artbear http://build.oscript.io/job/1Script/view/change-requests/job/PR-618/ вот тут собралось

2017-12-11 10:37 UTC, EvilBeaver approved these changes

2017-12-11 10:39 UTC, EvilBeaver commented
Ждем @artbear и вливаем

2017-12-11 14:26 UTC, artbear requested changes
Не увидел тестов значения этого параметра по умолчанию (в 1С это Истина)
Сценарий
+ я уже описывал - обычная запись текста открывает файл, а обычное чтение его прочитать не может.
  + параметр передается в конструкторе
  + параметр передается в методе Открыть

2017-12-12 10:23 UTC, dmpas commented
>Не увидел тестов значения этого параметра по умолчанию (в 1С это Истина)

вот знал же, что ты про это напишешь...

2017-12-12 18:17 UTC, artbear approved these changes

2017-12-13 08:05 UTC, dmpas commented
Я XML-DOC на ЧтениеТекста волью заодно, раз взялся. Сегодня сделаю, не вливайте.

2017-12-13 09:31 UTC, dmpas commented
Я всё

2017-12-13 09:34 UTC, merged

2017-12-13 11:08 UTC, EvilBeaver commented
Супер