Доработано null <-> Неопределено
EvilBeaver/OneScript pull request #634
Opened 2017-12-26 08:36 UTC by jdeshin

Поправил в соответствии с обсуждением #371

2017-12-26 08:46 UTC, nixel2007 commented
SonarQube analysis reported 1 issue

1. ![MAJOR][MAJOR] [ContextValuesMarshaller.cs#L108](https://github.com/EvilBeaver/OneScript/blob/ca535fba839827997624d9275d9e885827033f4f/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L108): Change this condition so that it does not always evaluate to 'true'; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2583)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-12-26 09:02 UTC, EvilBeaver requested changes
Поменять в условии на SimpleConstantValue.Undefined()

2017-12-26 09:02 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs
> +            if (value == null || value.DataType == DataType.NotAValidValue || value == ValueFactory.Create())
Это, как я понимаю, сделано для #371? Т.е. если передали Неопределено, то оно все равно смапится на null?

Кстати, вместо ValueFactory.Create() правильнее использовать ``SimpleConstantValue.Undefined()``

2017-12-26 09:02 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs
> +            if (objParam == null)
Блин, вот чует мое сердце, зря мы делаем безусловный маппинг простых типов в Неопределено, еще хлебнем с ним горя. Но аргументов придумать не могу.

2017-12-26 09:20 UTC, jdeshin commented on src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs
> +            if (value == null || value.DataType == DataType.NotAValidValue || value == ValueFactory.Create())
Могу переделать. Поправить или пока не надо?

2017-12-26 09:29 UTC, jdeshin commented on src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs
> +            if (value == null || value.DataType == DataType.NotAValidValue || value == ValueFactory.Create())
Поправил

2017-12-26 09:33 UTC, nixel2007 commented
SonarQube analysis reported 1 issue

1. ![MAJOR][MAJOR] [ContextValuesMarshaller.cs#L108](https://github.com/EvilBeaver/OneScript/blob/cf190695d52dbc97b0ca3529899424edfc1cb53f/src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs#L108): Change this condition so that it does not always evaluate to 'true'; some subsequent code is never executed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2583)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-12-26 09:40 UTC, jdeshin commented
Убрал проверку на null из 
```
var type = typeof(TRet); 
101             object objParam = (object)param; 
102             if (type == typeof(IValue)) 
103             { 
104                 if (param != null) 
105                     return (IValue)param; 
106                 else 
107                     return ValueFactory.Create(); 
108             } 
```
т.к. перед ней уже есть проверка на null

2017-12-26 10:00 UTC, jdeshin commented
Коллеги, не могли бы посмотреть, что не так? смотрю лог - куча варнингов и дебаггер не грузится, больше ничего найти не могу

2017-12-26 10:06 UTC, dmpas commented
@jdeshin на зип не смотри, а вот тест со списком значений - это косяк какой-то в допилке. У себя пробовал его пускать?

2017-12-26 10:08 UTC, jdeshin commented
Можешь ткнуть носом?

2017-12-26 10:15 UTC, jdeshin commented
Нашел, а как посмотреть код теста? И чегой-то он зеленый в дженкинсе?

2017-12-26 10:24 UTC, dmpas commented
@jdeshin где ж зелёный-то? http://build.oscript.io/blue/organizations/jenkins/1Script/detail/PR-634/3/tests

2017-12-26 10:38 UTC, dmpas commented on src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs
> +            if (objParam == null)
это ты классы простыми типами обозвал?

2017-12-26 12:30 UTC, jdeshin commented
@dmpas  Не там смотрел, в шагах. Поправил. Значение null возвращается в ConvertParam, если тип параметра не равен IValue и не равен IVariable и значение параметра = SimpleConstantValue.Undefined(). Проблема была в том, что IValueList хранит значения IValue, а ConvertParam конвертировала их в части Неопределено в null.

2017-12-27 07:54 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs
> +            if (objParam == null)
1С-ные простые типы имел в виду, т.е. автоконверсия (string)null -> Неопределено.

А "классовые" null у нас и так автоматом в Неопределено мапились, судя по коду.

2017-12-27 07:55 UTC, dmpas commented on src/ScriptEngine/Machine/Contexts/ContextValuesMarshaller.cs
> +            if (objParam == null)
да, про строки я не сообразил...

2017-12-27 12:21 UTC, nixel2007 commented
SonarQube analysis reported 10 issues

1. ![MAJOR][MAJOR] [TestNullConversion.cs#L84](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L84): Change this condition so that it does not always evaluate to 'true'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2589)
1. ![MINOR][MINOR] [TestNullConversion.cs#L95](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L95): Use the 'is' operator instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2219)
1. ![MINOR][MINOR] [TestNullConversion.cs#L153](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L153): Make this an auto-implemented property and remove its backing field. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2292)
1. ![MINOR][MINOR] [TestNullConversion.cs#L166](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L166): Make this an auto-implemented property and remove its backing field. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2292)
1. ![MINOR][MINOR] [TestNullConversion.cs#L179](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L179): Make this an auto-implemented property and remove its backing field. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2292)
1. ![MINOR][MINOR] [TestNullConversion.cs#L192](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L192): Make this an auto-implemented property and remove its backing field. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2292)
1. ![MINOR][MINOR] [TestNullConversion.cs#L205](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L205): Make this an auto-implemented property and remove its backing field. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2292)
1. ![MINOR][MINOR] [TestNullConversion.cs#L218](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L218): Make this an auto-implemented property and remove its backing field. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2292)
1. ![MINOR][MINOR] [TestNullConversion.cs#L231](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L231): Make this an auto-implemented property and remove its backing field. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2292)
1. ![MINOR][MINOR] [TestNullConversion.cs#L244](https://github.com/EvilBeaver/OneScript/blob/05945e10b8bf0b3a847537e40a305aeeab7d51ed/src/NUnitTests/TestNullConversion.cs#L244): Make this an auto-implemented property and remove its backing field. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2292)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-12-27 12:47 UTC, EvilBeaver commented on src/MarshallerTest/MarshallerTest.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
А зачем еще один проект, да еще и в виде EXE модуля?

2017-12-27 12:48 UTC, EvilBeaver commented on src/TestApp/App.xaml
> -﻿<Application x:Class="TestApp.App"
Эмм.... а куда делся проект TestApp, он удален??

2017-12-27 12:51 UTC, artbear commented on src/TestApp/App.xaml
> -﻿<Application x:Class="TestApp.App"
у автора даже в коммите так и написано - `Удалил TestApp` :(

2017-12-27 13:02 UTC, EvilBeaver commented on src/TestApp/App.xaml
> -﻿<Application x:Class="TestApp.App"
Это не значит, что это хорошо

2017-12-27 13:24 UTC, jdeshin commented on src/TestApp/App.xaml
> -﻿<Application x:Class="TestApp.App"
Мне сказал так сделать @dmpas. и я удалил

2017-12-27 13:26 UTC, jdeshin commented on src/MarshallerTest/MarshallerTest.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
У меня в этой ветке его нет

2017-12-27 13:31 UTC, jdeshin commented on src/MarshallerTest/MarshallerTest.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Удалил папку. Закомиттил

2017-12-27 13:35 UTC, dmpas commented on src/TestApp/App.xaml
> -﻿<Application x:Class="TestApp.App"
Виноват, пустил тропою ложной. Я про МаршаллерТест говорил.

2017-12-27 13:41 UTC, jdeshin commented on src/TestApp/App.xaml
> -﻿<Application x:Class="TestApp.App"
Его нет в солюшене. Папку удалил

2017-12-27 13:49 UTC, dmpas commented on src/TestApp/App.xaml
> -﻿<Application x:Class="TestApp.App"
TestApp надо вернуть. Он есть в солюшнене. Там два солюшна, один для ВизуалСтудии, второй - для других IDE.

2017-12-27 13:49 UTC, dmpas commented on src/TestApp/App.xaml
> -﻿<Application x:Class="TestApp.App"
можно ревёрт коммита сделать.

2017-12-27 18:47 UTC, nixel2007 commented
SonarQube analysis reported 2 issues

1. ![MINOR][MINOR] [TestNullConversion.cs#L82](https://github.com/EvilBeaver/OneScript/blob/a7ff12f421bb8e285cb8a29261667033e627596a/src/NUnitTests/TestNullConversion.cs#L82): Use the 'is' operator instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2219)
1. ![MINOR][MINOR] [TestNullConversion.cs#L191](https://github.com/EvilBeaver/OneScript/blob/a7ff12f421bb8e285cb8a29261667033e627596a/src/NUnitTests/TestNullConversion.cs#L191): Use the 'is' operator instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2219)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-12-27 19:10 UTC, dmpas approved these changes

2017-12-28 07:57 UTC, nixel2007 commented
SonarQube analysis reported 2 issues

1. ![MINOR][MINOR] [TestNullConversion.cs#L82](https://github.com/EvilBeaver/OneScript/blob/a8cacb841f5b974fcb5a021b4df3c608094297e7/src/NUnitTests/TestNullConversion.cs#L82): Use the 'is' operator instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2219)
1. ![MINOR][MINOR] [TestNullConversion.cs#L191](https://github.com/EvilBeaver/OneScript/blob/a8cacb841f5b974fcb5a021b4df3c608094297e7/src/NUnitTests/TestNullConversion.cs#L191): Use the 'is' operator instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2219)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-12-28 10:12 UTC, EvilBeaver approved these changes

2017-12-28 10:13 UTC, merged