Global context binary data
EvilBeaver/OneScript pull request #649
Opened 2018-01-08 19:45 UTC by jdeshin

Добавлены некоторые функции глобального контекста для работы с бинарными данными

2018-01-08 20:00 UTC, dmpas requested changes
`src/globalBinaryDataTest.os` - не нужен,
`src/UpgradeLog*.htm` - не нужны. Надо убрать лишние файлы.

2018-01-09 05:39 UTC, jdeshin commented
Все удалил. выгрузил

2018-01-09 05:58 UTC, dmpas commented
` src/UpgradeLog.htm` остался

2018-01-09 06:35 UTC, jdeshin commented
Мамой клянусь нету :) могу скриншот предоставить (если скажешь как его сюда вставить) или он не в src?

2018-01-09 07:04 UTC, dmpas commented
Если мамой, то как не поверить! Мой косяк : в пр этот файл как раз удаляется, а не добавляется. Всё чётко.

2018-01-09 07:20 UTC, jdeshin commented
Дык чо делать то?

2018-01-09 07:47 UTC, dmpas commented
@EvilBeaver там при сборке файл HTTPServices.dll не находит. Посмотришь, что там в BuildAll ??

2018-01-09 07:51 UTC, dmpas approved these changes

2018-01-09 12:40 UTC, merged