Httpservices cachingcompiled new
EvilBeaver/OneScript pull request #655
Opened 2018-01-10 10:42 UTC by jdeshin

Предлагаемые изменения, в соответствии с описанным в форуме:
1. Введена опция advancedFeatures для:
throw; // Must fail!
_hostedScript.SetGlobalEnvironment(
2. Обработка запроса заканчивается End()
3. configPath перенесен из static конструктора, дабы его можно было подпихнуть и он подхватился после recycling хотя бы в винде.

2018-01-10 13:56 UTC, EvilBeaver requested changes
/cc @dmpas @nixel2007

2018-01-10 13:56 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    // И что из-за одной dll, которой нет физически, она не используется и она есть в конфиге огрести неработоспособное приложение?
> из-за одной dll, которой нет физически, она не используется и она есть в конфиге огрести неработоспособное приложение

Блин, ну разумеется! Как минимум предупреждение выдать куда-то, но не совсем заигнорить!

2018-01-10 13:56 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                if (appSettings["advancedFeatures"] == "true")
Предлагаю другое название. HandlerLoadingPolicy: {strict|tolerant}, где tolerant игнорирует ошибки (твой вариант), а strict выдает их (мой).

2018-01-10 13:56 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                if (appSettings["errorActionPreferenceWhenHandlerCreating"] == "stop")
повесить на ту же опцию LoadingPolicy?

2018-01-10 13:56 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                // В Linux под Mono не работает подписка на изменение файла.
Предлагаю вынести в отдельный метод все, что в блоке try, чтобы код обработчика был более явным:

```c#
try
{
   callScriptHandler(context) 
}
finally
{
   context.Response.End;
}
```

2018-01-10 14:16 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    // И что из-за одной dll, которой нет физически, она не используется и она есть в конфиге огрести неработоспособное приложение?
Лог?

2018-01-10 14:51 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                // В Linux под Mono не работает подписка на изменение файла.
Готово, назвал CallScriptHandler

2018-01-10 14:52 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    // И что из-за одной dll, которой нет физически, она не используется и она есть в конфиге огрести неработоспособное приложение?
Сделал логгирование, аналогично тому, как в конструкторе

2018-01-10 14:54 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                if (appSettings["errorActionPreferenceWhenHandlerCreating"] == "stop")
Тут вроде как это разные вещи, расширенные фичи и политика загрузки.
Мож мне фичи то нужны, а загрузку хочу tolerant

2018-01-10 14:55 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                if (appSettings["errorActionPreferenceWhenHandlerCreating"] == "stop")
И мож таки stop/continue. Более привычны неанглоязычному человеку :)

2018-01-10 15:06 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                if (appSettings["errorActionPreferenceWhenHandlerCreating"] == "stop")
Заменил appSettings["errorActionPreferenceWhenHandlerCreating"]  на HandlerLoadingPolicy: {strict
Добавил при всех загрузках. Так норм?

2018-01-10 16:37 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                        WriteToLog(logWriter, "Error loading assembly: " + assemblyName + " " + ex.Message);
Вместо e.Message правильно логировать e.ToString()

К слову, С. Тепляков предлагал расстреливать тех, кто так не делает.

2018-01-10 16:37 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new ASPNetApplicationHost(), new AspEntryScriptSrc());
Это условие не нужно. Без установки среды не будут работать методы Сообщить и половина библиотек

2018-01-10 16:37 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new ASPNetApplicationHost(), new AspEntryScriptSrc());
Т.е. должно быть безусловная установка, без опции, к.м.к

2018-01-10 17:07 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                        WriteToLog(logWriter, "Error loading assembly: " + assemblyName + " " + ex.Message);
Это его личные так сказать трудности :), поправлю

2018-01-10 17:12 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new ASPNetApplicationHost(), new AspEntryScriptSrc());
Ну давай по третьему кругу :)
Что конкретно не будет работать? Исходя из моих тестов, страницы процессятся, библиотеки загружаются. Пожалуйста поясни, что не будет работать и зачем в веб-приложении Console.Writeline. На сколько я помню, ты говорил, что хост нужен для вывода Сообщить. Нам некуда чего-либо сообщать ибо это не консольное приложение. В 1С такая же ситуация на сервере. Ну таки что не будет работать? Таки нужно понимание.

2018-01-10 17:29 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                        WriteToLog(logWriter, "Error loading assembly: " + assemblyName + " " + ex.Message);
Поправил, обновил

2018-01-10 18:43 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new ASPNetApplicationHost(), new AspEntryScriptSrc());
Сделал и добавил дефолтные заглушки для host и исходного скрипта. Ключ в силе. У тебя там оказывается много интересного в глобальном контексте :) Действительно, если ты просто переносишь консольные скрипты - может отваливаться. По моему все, и волки сыты и овцы целы

2018-01-10 18:45 UTC, nixel2007 commented
SonarQube analysis reported 4 issues

1. ![CRITICAL][CRITICAL] [ASPNetNullApplicationHost.cs#L27](https://github.com/EvilBeaver/OneScript/blob/71d2d6d1a635db99442ad54a273c96e31814fb56/src/ASPNETHandler/ASPNetNullApplicationHost.cs#L27): Add a nested comment explaining why this method is empty, throw a 'NotSupportedException' or complete the implementation. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS1186)
1. ![CRITICAL][CRITICAL] [ASPNetNullApplicationHost.cs#L32](https://github.com/EvilBeaver/OneScript/blob/71d2d6d1a635db99442ad54a273c96e31814fb56/src/ASPNETHandler/ASPNetNullApplicationHost.cs#L32): Add a nested comment explaining why this method is empty, throw a 'NotSupportedException' or complete the implementation. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS1186)
1. ![MINOR][MINOR] [ASPNetNullApplicationHost.cs#L20](https://github.com/EvilBeaver/OneScript/blob/71d2d6d1a635db99442ad54a273c96e31814fb56/src/ASPNETHandler/ASPNetNullApplicationHost.cs#L20): Rename class 'ASPNetNullApplicationHost' to match camel case naming rules, consider using 'AspNetNullApplicationHost'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS101)
1. ![MINOR][MINOR] [AspNetNullEntryScriptSrc.cs#L20](https://github.com/EvilBeaver/OneScript/blob/71d2d6d1a635db99442ad54a273c96e31814fb56/src/ASPNETHandler/AspNetNullEntryScriptSrc.cs#L20): Rename class 'ASPNetNullEntryScriptSrc' to match camel case naming rules, consider using 'AspNetNullEntryScriptSrc'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS101)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-01-10 19:09 UTC, nixel2007 commented
SonarQube analysis reported 4 issues

1. ![CRITICAL][CRITICAL] [ASPNetNullApplicationHost.cs#L27](https://github.com/EvilBeaver/OneScript/blob/590f0f3541d57ae1322b52f73b6274546de29be4/src/ASPNETHandler/ASPNetNullApplicationHost.cs#L27): Add a nested comment explaining why this method is empty, throw a 'NotSupportedException' or complete the implementation. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS1186)
1. ![CRITICAL][CRITICAL] [ASPNetNullApplicationHost.cs#L32](https://github.com/EvilBeaver/OneScript/blob/590f0f3541d57ae1322b52f73b6274546de29be4/src/ASPNETHandler/ASPNetNullApplicationHost.cs#L32): Add a nested comment explaining why this method is empty, throw a 'NotSupportedException' or complete the implementation. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS1186)
1. ![MINOR][MINOR] [ASPNetNullApplicationHost.cs#L20](https://github.com/EvilBeaver/OneScript/blob/590f0f3541d57ae1322b52f73b6274546de29be4/src/ASPNETHandler/ASPNetNullApplicationHost.cs#L20): Rename class 'ASPNetNullApplicationHost' to match camel case naming rules, consider using 'AspNetNullApplicationHost'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS101)
1. ![MINOR][MINOR] [AspNetNullEntryScriptSrc.cs#L20](https://github.com/EvilBeaver/OneScript/blob/590f0f3541d57ae1322b52f73b6274546de29be4/src/ASPNETHandler/AspNetNullEntryScriptSrc.cs#L20): Rename class 'ASPNetNullEntryScriptSrc' to match camel case naming rules, consider using 'AspNetNullEntryScriptSrc'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS101)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-01-10 19:57 UTC, nixel2007 commented
SonarQube analysis reported 2 issues

1. ![MINOR][MINOR] [ASPNetNullApplicationHost.cs#L30](https://github.com/EvilBeaver/OneScript/blob/65ddc2d953a72b1b7c85784f3030deca3c050c4c/src/ASPNETHandler/ASPNetNullApplicationHost.cs#L30): Remove this redundant jump. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS3626)
1. ![MINOR][MINOR] [ASPNetNullApplicationHost.cs#L36](https://github.com/EvilBeaver/OneScript/blob/65ddc2d953a72b1b7c85784f3030deca3c050c4c/src/ASPNETHandler/ASPNetNullApplicationHost.cs#L36): Remove this redundant jump. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS3626)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-01-11 12:31 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new ASPNetApplicationHost(), new AspEntryScriptSrc());
@jdeshin я использую библиотеку логирования logos. Я же имею право это делать, как автор хттп-сервиса? Ну так вот, я хочу, чтобы вызовы моего сервиса логировались. Однако logos не работает, т.к. вызывает метод СтартовыйСценарий(). Кроме того, я не против, если в консоль моего xsp4 будет также выводиться лог. Я этот лог потом прочту, например, через docker logs. Вполне себе допустимое действие, однако в Консоль писать через Сообщить не могу, т.к. вместо хоста у меня заглушка.

Итого, просьба оставить на месте вызов метода SetGlobalEnvironment.

2018-01-11 12:34 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                if (appSettings["classicHTTPService"] == "true")
Зачем вот эти сложности и параметры? Что произойдет, если этого параметра вообще не будет, а SetGlobalEnvironment будет вызываться безусловно?

2018-01-11 12:34 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new AspNetNullApplicationHost(), new AspNetNullEntryScriptSrc());
NullEntryScript - это самообман, т.к. EntryScript существует - это сам файл os нашего сервиса. Стало быть, неправильно заменять результат этого метода на заглушку. Зачем? Чтобы что?

2018-01-11 13:14 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new AspNetNullApplicationHost(), new AspNetNullEntryScriptSrc());
ОК, тогда поясни плз. Это - конструктор хэндлера, он вызывается в общем случае до каких либо запросов. Формируется пул из нескольких экземпляров. При этом никаких скриптов и кода не выполняется. Что тут должно быть.
Случай номер два - один и тот-же хэндлер обрабатывает запросы к разным файлам os, Тогда его надо устанавливать как-то в ProcessRequest. Но ты его обозначил в конструкторе. Его можно перенести без влияния на инициализацию? И что туда подставлять?

2018-01-11 13:24 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                if (appSettings["classicHTTPService"] == "true")
Да ничего не произойдет, если класс Host будет типа заглушкой и поведение не будет отличаться от поведения платформы. У тебя же там console.writeline, цвета какие-то текста. Я, как лицо с ограниченными интеллектуальными возможностями - ниасилил. Я то не против, если это будет работать быстро, понятно и прозрачно. Ведь ты посмотрел заглушки и думаю - у тебя не возникло трудностей с пониманием. Я уже посмотрел и понял, что сообщить будет валиться с исключением, да, это неправильно и не соответствует поведению платформы. (Мог бы и объяснить :)) Там еще есть входные параметры - которых у нас нет, опять таки в силу того, что это не консольный скрипт. По хорошему, эти вопросы с хостом надо решать в движке, мало ли кто его куда захочет воткнуть. Но так быстрее и проще. Объясни плз. что ты собираешься делать в этих классах и не будет ли тормозить.
Надеюсь на понимание :)

2018-01-11 13:29 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new AspNetNullApplicationHost(), new AspNetNullEntryScriptSrc());
> один и тот-же хэндлер обрабатывает запросы к разным файлам os

Все, теперь вспомнил. Эта проблема не решается в текущем состоянии хостед. Поэтому, этот мой класс указывает на web.config

https://github.com/EvilBeaver/OneScript/blob/develop/src/ASPNETHandler/AspEntryScriptSrc.cs#L21

Это тот еще костыль, просто если стартовый скрипт будет указывать на несуществующий файл, то библиотеки поотваливаются многие (logos - точно). Они ожидают там файл.

2018-01-11 14:42 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new AspNetNullApplicationHost(), new AspNetNullEntryScriptSrc());
А web.config в общем случае может и не быть. Он может быть в рутовой папке, более "локальный" web.config переопределяет параметры более рутового.
Принципиально какой файл? Что они с ним делают?

2018-01-11 14:59 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new AspNetNullApplicationHost(), new AspNetNullEntryScriptSrc());
Вот поэтому на мой взгляд - опции рулят :) Понятно, что есть куча унаследованного кода, который адаптировать крайне сложно и он должен поддерживаться. С другой стороны - чисто веб-приложениям это не надо и я бы сказал, на мой взгляд,  в какой-то мере методологически вредно (ну организовывать логи через Сообщить к примеру) :). Так фигак - выставил опцию supportConsoleApp к примеру и все норм, не выставил - обычное веб приложение без требованиям к наличию файлов. Подумай, этож нормально и есть в том же 1С режим совместимости.

2018-01-11 15:26 UTC, artbear commented
На Ваш тред даже Гитхаб уже ругается :)


[image: Inline images 1]

PS упс, я еще чуток длину увеличил :)

С уважением,
Артур Аюханов

2018-01-11 17:59 GMT+03:00 jdeshin <notifications@github.com>:

> *@jdeshin* commented on this pull request.
> ------------------------------
>
> In src/ASPNETHandler/ASPNETHandler.cs
> <https://github.com/EvilBeaver/OneScript/pull/655#discussion_r160981944>:
>
> >                          }
>                      }
>                  }
>
>                  // метод настраивает внутренние переменные у SystemGlobalContext
> -                _hostedScript.SetGlobalEnvironment(new ASPNetApplicationHost(), new AspEntryScriptSrc());
> -                _hostedScript.Initialize();
> +                if (appSettings["classicHTTPService"] == "true")
> +                    _hostedScript.SetGlobalEnvironment(new AspNetNullApplicationHost(), new AspNetNullEntryScriptSrc());
>
> Вот поэтому на мой взгляд - опции рулят :) Понятно, что есть куча
> унаследованного кода, который адаптировать крайне сложно и он должен
> поддерживаться. С другой стороны - чисто веб-приложениям это не надо и я бы
> сказал, на мой взгляд, в какой-то мере методологически вредно (ну
> организовывать логи через Сообщить к примеру) :). Так фигак - выставил
> опцию supportConsoleApp к примеру и все норм, не выставил - обычное веб
> приложение без требованиям к наличию файлов. Подумай, этож нормально и есть
> в том же 1С режим совместимости.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EvilBeaver/OneScript/pull/655#discussion_r160981944>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACyRcTcULk4X4_vRGHV7HpgWhqlahZRKks5tJiHFgaJpZM4RZHvg>
> .
>

2018-01-11 19:52 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                if (appSettings["classicHTTPService"] == "true")
Тормозить не будет, а эти классы исключительно для штатных библиотек 1Script, которые активно юзают стартовый скрипт и Сообщить

2018-01-11 19:54 UTC, EvilBeaver commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new AspNetNullApplicationHost(), new AspNetNullEntryScriptSrc());
ОО! Идея. Давай вместо туманной опции classicHTTPService введем две другие: startupScript и enableEcho

Первая - что написали, то и будет возвращено в "Стартовый сценарий". Ничего не написали - будет NullScript

Вторая - включен Сообщить - пишем в консоль. Выключен - Null-объект
Тормозить не будет.

2018-01-12 05:04 UTC, jdeshin commented on src/ASPNETHandler/ASPNETHandler.cs
> +                    _hostedScript.SetGlobalEnvironment(new AspNetNullApplicationHost(), new AspNetNullEntryScriptSrc());
Давай :). Тогда наверное прими pr там логи и политика загрузки и добавь опции как надо.

2018-01-12 07:12 UTC, merged