Fix #688. Запрет закрывающей запятой перед скобкой в определении функции
EvilBeaver/OneScript pull request #689
Opened 2018-01-27 10:11 UTC by nixel2007

2018-01-29 08:15 UTC, EvilBeaver requested changes

2018-01-29 08:15 UTC, EvilBeaver commented on src/ScriptEngine/Compiler/Compiler.cs
> +            if (_previousExtractedLexem.Token == Token.Comma)
Для данной задачи глобальная переменная совершенно лишняя. Узнать что было перед окончанием цикла можно и локальной переменной previous.

2018-01-29 08:18 UTC, nixel2007 commented on src/ScriptEngine/Compiler/Compiler.cs
> +            if (_previousExtractedLexem.Token == Token.Comma)
я думал над этим. но тогда сохранение в локальную переменную нужно будет делать в 3-4 местах, перед каждым NextToken(), т.е. можно пропустить. а в текущем варианте оно зашито внутрь. 

меняю на локальную?

2018-01-29 08:27 UTC, EvilBeaver commented on src/ScriptEngine/Compiler/Compiler.cs
> +            if (_previousExtractedLexem.Token == Token.Comma)
Мне кажется, что можно вообще без этой переменной... Пусть пока повисит, я попозже код курну, сейчас некогда, ок?

2018-01-29 08:27 UTC, nixel2007 commented on src/ScriptEngine/Compiler/Compiler.cs
> +            if (_previousExtractedLexem.Token == Token.Comma)
да, конечно.

2018-01-29 18:33 UTC, EvilBeaver commented
@nixel2007 посмотришь?

2018-01-29 20:02 UTC, nixel2007 commented
@EvilBeaver у меня немного мозг выкручивается от пост-обработки токенов, но вроде все верно.

А тесты падают по связанной причине или по великому ХЗ?

P. S. Запилил пулл-реквестик в грамматику, ага...)

2018-01-30 07:14 UTC, EvilBeaver commented
По данному PR тесты прошли, упало дальше на создании DEB-RPM.

2018-01-30 07:15 UTC, merged