#696 Feature/export method info
EvilBeaver/OneScript pull request #698
Opened 2018-02-02 11:51 UTC by nixel2007

2018-02-02 11:59 UTC, artbear requested changes

2018-02-02 11:59 UTC, artbear commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +                if (item.Signature.IsExport) { continue; }
Почему здесь должны пропускаться экспортные методы?

2018-02-02 11:59 UTC, artbear commented on src/ScriptEngine.HostedScript/Library/Reflector.cs
> +                if (methInfo.IsExport) { continue; }
Условие нужно заменить на обратное.
Нам же нужно получить экспортные методы, а по условию они пропускаются.

2018-02-02 11:59 UTC, nixel2007 commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +                if (item.Signature.IsExport) { continue; }
потому что кривожоп

2018-02-03 21:35 UTC, EvilBeaver requested changes

2018-02-03 21:35 UTC, EvilBeaver commented on src/ScriptEngine/Compiler/Compiler.cs
> +            // TODO: deprecate?
Пока не надо. Неизвестно где выстрелит

2018-02-03 21:35 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs
> +                if (!item.Signature.IsExport) { continue; }
Нет, вот здесь неверно будет. GetScriptMethod это внутренний метод класса. Здесь должны быть видны неэкспортные

2018-02-04 19:46 UTC, EvilBeaver approved these changes

2018-02-04 19:49 UTC, nixel2007 commented
Мержим?

2018-02-04 19:50 UTC, merged