Feature/issues 453
EvilBeaver/OneScript pull request #719
Opened 2018-02-15 22:22 UTC by fishca

https://github.com/EvilBeaver/OneScript/issues/453 - Проба пера в локализации

2018-02-15 22:33 UTC, nixel2007 commented
SonarQube analysis reported 4 issues

1. ![CRITICAL][CRITICAL] [ExecuteScriptBehavior.cs#L56](https://github.com/EvilBeaver/OneScript/blob/07470fc9e1afdd64ef1da8b46742f924f35c6977/src/oscript/ExecuteScriptBehavior.cs#L56): Remove this set, which updates a 'static' field from an instance method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2696)
1. ![CRITICAL][CRITICAL] [Program.cs#L26](https://github.com/EvilBeaver/OneScript/blob/07470fc9e1afdd64ef1da8b46742f924f35c6977/src/oscript/Program.cs#L26): Change the visibility of 'LocaleMessage' or make it 'const' or 'readonly'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS2223)
1. ![MINOR][MINOR] [Program.cs#L26](https://github.com/EvilBeaver/OneScript/blob/07470fc9e1afdd64ef1da8b46742f924f35c6977/src/oscript/Program.cs#L26): Make this field 'private' and encapsulate it in a 'public' property. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS1104)
1. ![MINOR][MINOR] [launchSettings.json#](https://github.com/EvilBeaver/OneScript/blob/07470fc9e1afdd64ef1da8b46742f924f35c6977/src/oscript/Properties/launchSettings.json#): Add an empty new line at the end of this file. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=json%3Aempty-line-end-of-file)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-02-16 06:00 UTC, fishca commented
А покритиковать? Есть какие-то замечания по предложенному решению?

2018-02-16 19:08 UTC, EvilBeaver requested changes
Кажется переделка должна быть глубже. Сейчас никакой архитектуры по локализации нет, поэтому вкрячивать костыли приходится то тут то там.

2018-02-16 19:08 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/SystemEnvironmentContext.cs
> +            var hostedScript = new HostedScriptEngine();
Ой-вей. Не, давайте лучше сделаем другой более легкий способ получения конфига, но не через создание еще одного движка. Это перебор, имхо

2018-02-16 19:08 UTC, EvilBeaver commented on src/oscript/Program.cs
> +        public static LocaleApp LocaleMessage = LocaleApp.en;
А вот вопрос - какой язык по умолчанию? Одним неудобно английский, другим неудобно периодические кракозябры в консоли. @nixel2007 @JohnyDeath ??

2018-02-16 19:08 UTC, EvilBeaver commented on src/oscript/Properties/launchSettings.json
> +    "oscript": {
Этот файл не нужен в репо. Его надо добавить в гитигнор

2018-02-16 19:08 UTC, EvilBeaver commented on src/oscript/ShowUsageBehavior.cs
> +            else if (culture.Name.Equals("en-US"))
А как насчет локали en/ru, добавленной в другом файле? 

Кажется, получается какое-то несогласованное управление языком вывода. Думаю, тут надо глубже перепроектировать это дело, ибо изначально я его вообще никак не проектировал и получился вот такой разброс настроек тут и там.

Мне видится опция текущей локали в oscript.cfg (возможно, еще и ключ ком. строки, но параметр в файле точно нужен). Затем нужна глобальная служба получения локализованных текстов. И... не знаю, все это склеить вместе еще как-то

2018-02-16 19:30 UTC, nixel2007 commented on src/oscript/Program.cs
> +        public static LocaleApp LocaleMessage = LocaleApp.en;
@kuntashov предлагал брать системный язык

2018-02-17 20:45 UTC, JohnyDeath commented on src/oscript/Program.cs
> +        public static LocaleApp LocaleMessage = LocaleApp.en;
Согласен с @nixel2007 и @kuntashov

2018-02-20 08:20 UTC, EvilBeaver commented on src/oscript/Program.cs
> +        public static LocaleApp LocaleMessage = LocaleApp.en;
Дело в том, что нет такого понятия, как "системный язык". Вернее, у него много разных трактовок.

2018-02-20 08:22 UTC, EvilBeaver commented
@fishca там тест один упал, проверяющий выхлоп oscript.exe без параметров.

http://build.oscript.io/job/1Script/view/change-requests/job/PR-719/1/testReport/(root)/process/Windows_testing___%D0%A2%D0%B5%D1%81%D1%82%D0%94%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD_%D0%9F%D1%80%D0%BE%D1%87%D0%B8%D1%82%D0%B0%D1%82%D1%8C%D0%92%D1%8B%D0%B2%D0%BE%D0%B4Oscript%D0%A1%D1%80%D0%B0%D0%B7%D1%83/

2019-01-14 06:18 UTC, alexkmbk commented on src/oscript/ShowUsageBehavior.cs
> +            else if (culture.Name.Equals("en-US"))
@EvilBeaver 

> Мне видится опция текущей локали в oscript.cfg


Так в итоге, сделали параметр в oscript.cfg? На текущий момент есть ли где-то параметр в каком-либо конфигурационном файла, для задания языка?

2019-04-26 14:34 UTC, closed without merging