fix #700
EvilBeaver/OneScript pull request #721
Opened 2018-02-18 14:59 UTC by DJYar

Распаковка аргументов из массива (issue #700 ) 
Проверял на 8.3.11.2867 и в OneScript-- теперь код работает одинаково.

2018-02-18 16:13 UTC, nixel2007 commented
@EvilBeaver сборка vsce падает. Ты на слейве не крутил ничего?

2018-02-20 08:13 UTC, EvilBeaver requested changes

2018-02-20 08:13 UTC, EvilBeaver commented on src/ScriptEngine/Machine/Core.cs
> +        public string AlterName;
Везде в программе используем для англ. синонима термин Alias. Предлагаю сделать единообразно и в этом случае.

2018-02-20 08:13 UTC, EvilBeaver commented on src/ScriptEngine/Machine/MachineInstance.cs
> +            } while (false);
Не совсем понятна магия с do.. while(false). Для чего нужен однопроходный цикл?
И второе - не лучше ли вынесли вот этот type 2 subroutine в отдельный метод? Код вызова конструктора и так переусложнен, его неплохо бы порефакторить.

2018-02-20 08:13 UTC, EvilBeaver commented on src/ScriptEngine/Machine/TypeManager.cs
> +                    AlterName = alterAlias,
Поменять на термин "Alias" (см. выше)

2018-02-24 20:03 UTC, EvilBeaver commented
@DJYar тесты попадали в большом количестве. Просьба исправить: http://build.oscript.io/job/1Script/view/change-requests/job/PR-721/5/testReport/

2018-02-24 22:07 UTC, DJYar commented
@EvilBeaver я PR прикрою, чтобы в CI он не собирался. Время свободное появится -- у себя правки внесу и открою другой PR с учетом замечаний.

2018-02-24 22:07 UTC, closed without merging

2019-08-26 08:25 UTC, EvilBeaver commented
@DJYar конечно, это некропостинг, но может вернемся к вопросу?