fix #763 + tests
EvilBeaver/OneScript pull request #765
Opened 2018-06-06 10:08 UTC by Mr-Rm

2018-06-06 10:11 UTC, dmpas approved these changes

2018-06-06 11:18 UTC, artbear requested changes
Неточные тесты, лучше их исправить.

2018-06-06 11:18 UTC, artbear commented on tests/global-funcs.os
> +	ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя", "Имя");
Дубль кода в 2х местах:
```
+	ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя", "Имя");
+	юТест.ПроверитьРавенство(Источник.Фамилия, Приемник.Фамилия);
+	юТест.ПроверитьРавенство(Источник.Имя, Приемник.Имя);
+	юТест.ПроверитьРавенство(Неопределено, Приемник.Отчество);
```

2018-06-06 11:18 UTC, artbear commented on tests/global-funcs.os
> +		юТест.ПрерватьТест("Заполнение несуществующего свойства должно выдавать исключение, но не выдало");
Неправильно юзать `юТест.ПрерватьТест` внутри блока `Попытка-Исключение`
т.к. прерывание теста - это всего лишь выброс исключения.

А сейчас это исключение будет скрыто внутри блока `Попытка-Исключение`, что не приведет к падению теста :(

2018-06-06 11:18 UTC, artbear commented on tests/global-funcs.os
> +		юТест.ПрерватьТест("Заполнение несуществующего свойства должно выдавать исключение, но не выдало");
Используй булеву переменную, которая принимает разные значения в блоке и исключении, и прерывает тест в случае неверного значения

2018-06-06 11:18 UTC, artbear commented on tests/global-funcs.os
> +		юТест.ПрерватьТест("Заполнение несуществующего свойства должно выдавать исключение, но не выдало");
Аналогично неверно скрывать прерывание теста

2018-06-06 11:18 UTC, artbear commented on tests/global-funcs.os
> +		юТест.ПрерватьТест("Заполнение несуществующего свойства должно выдавать исключение, но не выдало");
Аналогично неверно скрывать прерывание теста

2018-06-06 11:18 UTC, artbear commented on tests/global-funcs.os
> +	ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя", "Несуществующее");
Здесь лучше выбрасывать исключение, т.к. явно указали неверное значение.

2018-06-06 11:40 UTC, Mr-Rm commented on tests/global-funcs.os
> +	ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя", "Несуществующее");
Поведение 
`ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя", "Несуществующее");`
как раз и обсуждалось в issue #763. Было решено сделать совместимо с 1С.

2018-06-06 12:00 UTC, Mr-Rm commented on tests/global-funcs.os
> +		юТест.ПрерватьТест("Заполнение несуществующего свойства должно выдавать исключение, но не выдало");
Да, с исключениями понятно. Получается, что один тест - один вариант - одна функция. Либо нужен какой-то дополнительный механизм для тестирования множества вариантов.

2018-06-06 12:04 UTC, artbear commented on tests/global-funcs.os
> +		юТест.ПрерватьТест("Заполнение несуществующего свойства должно выдавать исключение, но не выдало");
> Получается, что один тест - один вариант - одна функция. 

Вообще так и нужно делать.
Один сценарий/тест.кейс = 1 тест.
А в сценарии не рекомендуется использовать больше одной проверки.

2018-06-06 12:36 UTC, Mr-Rm commented on tests/global-funcs.os
> +		юТест.ПрерватьТест("Заполнение несуществующего свойства должно выдавать исключение, но не выдало");
Трудно таким образом писать много тестов для проверки всех вариантов. А тестировать надо в том числе и редкие случаи, как показал разбор issue #759 .

2018-06-06 13:59 UTC, Mr-Rm commented
Не пойму, что со сборкой?  Какие ошибки?

2018-06-07 11:34 UTC, EvilBeaver reviewed
На редкость приятный пулреквест! Спасибо!

Есть один вопрос - ниже, по остальному - отлично

2018-06-07 11:34 UTC, EvilBeaver commented on tests/global-funcs.os
> +	ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя", "Имя");
Критикуешь - предлагай )

2018-06-07 11:34 UTC, EvilBeaver commented on tests/global-funcs.os
> +	ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя", "Несуществующее");
@Mr-Rm а разве 1С здесь не выбрасывает исключение?

2018-06-07 12:23 UTC, Mr-Rm commented
Ещё не всё, добавлю проверку типов.
Попутно выявилась ошибка в постороннем тесте (tests\stringoperations.os).

2018-06-07 12:26 UTC, Mr-Rm commented on tests/global-funcs.os
> +	ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя", "Несуществующее");
Нет, содержимое строки с исключениями не учитывается.

2018-06-07 13:45 UTC, nixel2007 commented
SonarQube analysis reported 1 issue

1. ![CRITICAL][CRITICAL] [SystemGlobalContext.cs#L501](https://github.com/EvilBeaver/OneScript/blob/239e56566bb0209bab679c97a769cd6c3e55dac9/src/ScriptEngine.HostedScript/Library/SystemGlobalContext.cs#L501): Refactor this method to reduce its Cognitive Complexity from 23 to the 15 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.silverbulleters.org/coding_rules#rule_key=csharpsquid%3AS3776)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'

2018-06-07 14:01 UTC, artbear commented on tests/global-funcs.os
> +	ЗаполнитьЗначенияСвойств(Приемник, Источник, "Фамилия,Имя", "Имя");
Вынести в метод-хелпер

2018-06-07 14:07 UTC, artbear approved these changes
Все хорошо.

У меня только замечания к дублированию кода (4 строки в 2х местах или более)

2018-06-08 06:57 UTC, merged