Localization
EvilBeaver/OneScript pull request #848
Opened 2019-01-23 12:37 UTC by alexkmbk

Реализована задача описанная в этом комментарии - https://github.com/EvilBeaver/OneScript/issues/453#issuecomment-454295409

2019-01-23 12:42 UTC, alexkmbk commented
Под Linux не тестировал (сходу не получилось организовать тестирование)

2019-01-23 13:36 UTC, dmpas requested changes

2019-01-23 13:36 UTC, dmpas commented on src/ScriptEngine.HostedScript/Library/LanguagesEnum.cs
> +        Russian
пробелотабы

2019-01-23 13:36 UTC, dmpas commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +                    else
тут лишнее впилево

2019-01-23 13:39 UTC, dmpas requested changes

2019-01-23 13:39 UTC, dmpas commented on src/ScriptEngine.HostedScript/HostedScriptEngine.cs
> +            if ((SystemLanguageStr != null && SystemLanguageStr.ToLower() == "ru") || (SystemLanguageStr == null && System.Globalization.CultureInfo.CurrentCulture.EnglishName.ToLower().Contains("rus
лучше не так, по-1С-ному, а через шарповый Compare

2019-01-23 14:25 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/HostedScriptEngine.cs
> +            if ((SystemLanguageStr != null && SystemLanguageStr.ToLower() == "ru") || (SystemLanguageStr == null && System.Globalization.CultureInfo.CurrentCulture.EnglishName.ToLower().Contains("rus
Исправил, но имхо наглядность кода хуже с Compare

2019-01-23 14:38 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/LanguagesEnum.cs
> +        Russian
вроде бы исправил

2019-01-23 15:54 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Json/JSONReader.cs
> +                    else
вроде бы исправил

2019-01-23 16:42 UTC, dmpas approved these changes

2019-01-23 16:42 UTC, dmpas commented
по коду нормально. Но всё же меня смущает логика двух намертво зашитых языков.

2019-01-23 16:56 UTC, alexkmbk commented
> по коду нормально. Но всё же меня смущает логика двух намертво зашитых языков.

Так я постановку писал, приглашал к обсуждению, сообщество ответило молчаливым согласием :-) 
Вообще же, идея двух языков в том, что вряд ли кто-то будет писать сообщения пользователю на языке, отличным от этих двух (конкретно в скриптах OneScript), и оттого нет смысла эти языки как либо идентифицировать, упрощая получаем преимущество, мы железно либо получим русский язык либо английский, даже если система у пользователя скажем вьетнамская, что имхо хорошо и правильно.

2019-01-24 04:56 UTC, alexkmbk commented
@dmpas Но в принципе, можно и поменять концепцию, например, захардкодить только  ISO 639-1 код английского языка в функции Nstr, то есть скажем выводить текст с кодом En если нет текста для текущего языка. А все остальные остальные языки определять автоматически по значению CultureInfo.TwoLetterISOLanguage. И от перечисления LanguagesEnum вовсе можно отказаться, и сделать переменную SytemLanguage строкового типа, и она будет хранить значение ISO 639-1 кода.

2019-01-24 08:38 UTC, EvilBeaver requested changes

2019-01-24 08:38 UTC, EvilBeaver commented on src/1Script_Mono.sln
> +		{F062D1D9-D307-492A-A56B-FF3C55F8F6C0}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
Модификацию sln точно надо коммитить?

2019-01-24 08:38 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/HostedScriptEngine.cs
> +            if ((SystemLanguageStr != null && String.Compare(SystemLanguageStr, "ru", true) >= 0) || (SystemLanguageStr == null && String.Compare(System.Globalization.CultureInfo.CurrentCulture.Engli
Тут избыточные проверки на Null в блоках ИЛИ. На null достаточно проверить один раз и далее проверять только сами тексты. Ну и в целом - довольно длинное условие сложно понимать.

2019-01-24 08:38 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/ScriptEngine.HostedScript.csproj
> +    <Compile Update="Library\LanguagesEnum.cs">
Странно, зачем этот блок, оно должно автоматически добавлять все .cs файлы в проект.

2019-01-24 08:38 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/Locale.cs
> +﻿using System;
Мне кажется, эту класс надо унести в сборку ScriptingEngine.dll, чтобы там можно было локализовать тексты исключений и разные системные сообщения.

2019-01-24 10:32 UTC, alexkmbk commented on src/1Script_Mono.sln
> +		{F062D1D9-D307-492A-A56B-FF3C55F8F6C0}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
> Модификацию sln точно надо коммитить?

Нет, ненадо

2019-01-24 10:37 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/HostedScriptEngine.cs
> +            if ((SystemLanguageStr != null && String.Compare(SystemLanguageStr, "ru", true) >= 0) || (SystemLanguageStr == null && String.Compare(System.Globalization.CultureInfo.CurrentCulture.Engli
Думаю переделать на более универсальный механизм.

2019-01-24 10:55 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Locale.cs
> +﻿using System;
> Мне кажется, эту класс надо унести в сборку ScriptingEngine.dll, чтобы там можно было локализовать тексты исключений и разные системные сообщения.

а в чем разница по сравнению с текущим решением? Идея в том, что для вывода системных сообщений необходимо будет использовать функцию Locale.NStr() она доступна отовсюду.

2019-01-24 11:18 UTC, alexkmbk commented
> Под Linux не тестировал (сходу не получилось организовать тестирование)

последние изменения протестировал на Ubuntu 14

2019-01-24 14:08 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/Library/Locale.cs
> +﻿using System;
Перенёс в ScriptEngine.Machine

2019-01-29 14:10 UTC, alexkmbk commented on src/ScriptEngine.HostedScript/ScriptEngine.HostedScript.csproj
> +    <Compile Update="Library\LanguagesEnum.cs">
Требуется ли что-то еще поменять?

2019-01-31 10:08 UTC, merged

2019-01-31 11:19 UTC, alexkmbk commented
Ура!