добавил Language как ресурс Standalone
EvilBeaver/OneScript pull request #969
Opened 2020-01-09 08:33 UTC by zeratulayuris

По просьбе трудящихся

2020-01-13 08:54 UTC, EvilBeaver requested changes

2020-01-13 08:54 UTC, EvilBeaver commented on src/StandaloneRunner/StandaloneRunner.csproj
>      <EmbeddedResource Include="Newtonsoft.Json.dll" />
Нужен еще post build action для копирования language.dll в каталог standalone по аналогии с другими dll

2020-01-13 09:52 UTC, zeratulayuris commented on src/StandaloneRunner/StandaloneRunner.csproj
>      <EmbeddedResource Include="Newtonsoft.Json.dll" />
Так вот как оно подтягивается! Я когда смотрел, не увидел сразу (

2020-01-14 04:57 UTC, merged

2020-01-31 09:42 UTC, EvilBeaver commented
@zeratulayuris подай реквест на награду в https://github.com/EvilBeaver/OneScript/issues/949 по ссылочке

2020-01-31 09:51 UTC, zeratulayuris commented
> @zeratulayuris подай реквест на награду в #949 по ссылочке

![image](https://user-images.githubusercontent.com/9881249/73529806-21da4a00-4439-11ea-9c7d-00a2b5a286d3.png)

что-то пошло не так.

2020-01-31 09:58 UTC, zeratulayuris commented
Похоже, провайдер на работе то ещё дно, дофига всего блокирует. Из дома придётся пробовать.