LDAP features
EvilBeaver/OneScript pull request #972
Opened 2020-01-21 05:09 UTC by zeratulayuris

Минимально работающие LDAP-объекты.

- [ ] Получение свойств записи дерева
- [ ] Поиск записей в дереве
- [ ] Аутентификация

2020-01-21 09:25 UTC, asosnoviy commented
Огнище! Только может это в отдельную либу нада?

2020-01-21 10:03 UTC, zeratulayuris commented
@asosnoviy насчет либы хз, мне хотелось именно нативно в языке поддержку получить. В целом результат меня уже устраивает по функционалу, ещё попробую сборку osweb с этой фичей - если (когда!) взлетит, будет совсем огонь, проект на работе резко ускорится за счет ухода с COM-объектов.

2020-01-21 10:08 UTC, asosnoviy commented
Я имел ввиду компаненту расширяющую движок аля ftp или InternetMail.

2020-01-21 10:31 UTC, dmpas commented on src/ScriptEngine.HostedScript/Library/LDAP/DirectoryEntry.cs
> +            get { return "********"; }
Мне кажется, геттер тут вообще не нужен.

2020-01-21 12:34 UTC, zeratulayuris commented on src/ScriptEngine.HostedScript/Library/LDAP/DirectoryEntry.cs
> +            get { return "********"; }
Думаешь, лучше исключение при попытке прочитать свойство?

2020-01-21 12:39 UTC, dmpas commented on src/ScriptEngine.HostedScript/Library/LDAP/DirectoryEntry.cs
> +            get { return "********"; }
Просто выпилить геттер. А исключение движок уже сам будет бросать.

2020-01-21 17:54 UTC, khorevaa commented
Я за включение в движок!! Т.к. dll потом не пересобираете под новые версии движков

2020-01-21 17:57 UTC, nixel2007 commented
К сожалению, в словах @khorevaa есть зерно истины :(

2020-01-23 07:46 UTC, zeratulayuris commented on src/ScriptEngine.HostedScript/Library/LDAP/DirectoryEntry.cs
> +            get { return "********"; }
Выпилено

2020-01-24 08:45 UTC, EvilBeaver commented
@dmpas что думаешь насчет выделения в либу или включения в движок?

2020-01-24 08:55 UTC, EvilBeaver requested changes

2020-01-24 08:55 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/LDAP/DirectorySearcher.cs
> +                return ValueFactory.Create();
По-моему, marshaller сам возвращает Неопределено, если вернули из метода null, не?

т.е. return null достаточно

2020-01-24 08:55 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/LDAP/DirectorySearcher.cs
> +    [ContextClass("ПоискВКаталоге", "DirectorySearcher")]
Мне не нравится название класса. Оно слишком общее, если это включать в движок. Представьте, если никто не работает с LDAP и в коде видит "Новый ПоискВКаталоге" Какие ассоциации? Поиск на диске. А речь, оказывается про LDAP. Если это хотите выносить в движок, то API нужно более тонко специфицировать. Поэтому, мне кажется, что это больше на либу похоже.

2020-01-24 08:55 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/LDAP/PropertyCollection.cs
> +    [ContextClass("КоллекцияСвойств", "PropertyCollection")]
Опять, слишком общее имя класса для включения в движок

2020-01-24 08:55 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/LDAP/PropertyCollection.cs
> +        public override int GetPropCount()
Можно для краткости использовать синтаксис ``int GetPropCount() => _values.Count;``

2020-01-24 08:55 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/LDAP/PropertyValueCollection.cs
> +    [ContextClass("КоллекцияЗначенийСвойства", "PropertyValueCollection")]
То же самое, LDAP-specific

2020-01-24 08:55 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/LDAP/DirectorySearcher.cs
> +            if ((propertiesToLoad ?? ValueFactory.Create()).GetRawValue() is ArrayImpl val_ptl)
Сложная конструкция.

``propertiesToLoad?.GetRawValue() is ArrayImpl`` проще

2020-01-24 08:55 UTC, EvilBeaver commented on src/ScriptEngine.HostedScript/Library/LDAP/SearchResult .cs
> +    [ContextClass("РезультатПоиска", "SearchResult")]
Ну а это и вовсе мега-общее название для класса.

2020-01-24 08:55 UTC, dmpas commented
Я за либу.

2020-01-24 08:56 UTC, EvilBeaver commented
> Я за либу.

Я тоже за либу, плюс смотри мои каменты к ревью.

2020-01-24 10:03 UTC, zeratulayuris commented
> > Я за либу.
> 
> Я тоже за либу, плюс смотри мои каменты к ревью.

По ревью - всё, что не относится к именованию - поправлю прямо тут.
Насчёт именования и вынесения в либу - можно ссылку на пример либы? Тогда перетащу в либу и именование можно будет оставить.

2020-01-29 10:17 UTC, zeratulayuris commented
PR закрываю, функционал переехал в библиотеку.

2020-01-29 10:17 UTC, closed without merging